# 1. Power Method

## 1.1. Cơ sở lý thuyết 

Ta giả sử ma trân $\mathbf{A}$ vuông, thực, mỗi trị riêng bội $k$ có đủ $k$ véc tơ riêng độc lập tuyến tính.
Như vậy, ta giả sử $\mathbf{A}$ cấp $n$ có đủ $n$ trị riêng thực hoặc phức (đơn hoặc bội) được đánh số theo thứ tự có mô đun giảm dần. Khi đó, hệ véc tơ riêng tương ứng sẽ độc lập tuyến tính. 

Ta lấy tập các véc tơ riêng đó là một cơ sở của column space của $\mathbf{A}$, và khi đó mọi $\mathbf{y} \in \mathbb{R}^n$ đều được biểu diễn theo cơ sở này.  

\begin{equation}
\mathbf{y} = \sum_{i=1}^{n}c_i\mathbf{x}_i
\end{equation}

Ta chọn véc tơ $\mathbf{y}$ có $c_1 \neq 0$. 

Tuy nhiên, vấn đề ở đây là ta chưa biết được tập các véc tơ riêng $x_i$ của $\mathbf{A}$, thì khi đó ta tính các $c_i$ kiểu gì được???

## Vấn đề hiển thị thông tin: 

- Phải hiển thị được các vòng lặp 

## TH1: Trị riêng trội $\lambda_1$ thực, đơn

\begin{equation}
\lambda_1 = \frac{(\mathbf{A}^{m+1}\mathbf{y})_j}{(\mathbf{A}^m\mathbf{y})_j} \quad j = \overline{1, n}  \quad (2)
\end{equation}

- Điều kiện dừng khi các tỉ số (2) xấp xỉ bằng nhau. 

- Cách làm: Chọn véc tơ $y$ có $c_1 \neq 0$.  

## Chương trình: 

In [63]:
import numpy as np
import math

### Hàm tính chuẩn cực đại (chuẩn hàng) của véc tơ

- Note: Chuẩn này có thể được thực hiện đơn giản bởi hàm abs() và max() của numpy.

In [2]:
def maxVectorNorm(x): 
    n = len(x)
    max = abs(x[0])
    
    for i in range(1, n): 
        if abs(x[i]) > max: 
            max = abs(x[i])
            
    return max

### Hàm đánh giá sai số giữa các phần tử của lambda_vector: 

In [3]:
def error_estimate(lambdaVector, eps): 
    # tìm phần tử có trị tuyệt đối min trong lambda_vector: 
    minL = abs(lambdaVector.copy()).min()
            
    # tính hiệu của các phần tử còn lại với phần tử min vừa tìm được ở trên: 
    diffVector = abs(lambdaVector.copy()) - minL
        
    # Tính sai số bằng chuẩn cực đại của véc tơ. (chuẩn hàng của véc tơ)
    maxL = maxVectorNorm(diffVector)
            
    return maxL

In [43]:
def TH1(A, y, eps): 
    # hai giá trị lặp đầu tiên. 
    Ay_0 = np.matmul(A, y)
    Ay = np.matmul(A, Ay_0)
    
    lambdaVector = Ay / Ay_0  # chia các phần tử tương ứng của hai véc tơ cho nhau. 
    iter =  1 
    
    # đánh giá độ gần nhau của các phần tử của véc tơ lambda: 
    # chọn phần tử có trị tuyệt đối nhỏ nhất trong véc tơ lambda. Lấy trị tuyệt đối của hiệu của các phần tử còn lại với phần 
    # tử min vừa tìm được. 
    # xét hiệu max. nếu hiệu max < epsilon thì dừng, không thì tiếp tục vòng lặp. 
    
    while error_estimate(lambdaVector, eps) >= eps: 
        # cập nhật lại số vòng lặp 
        iter += 1
        
        # cập nhật lại Ay và Ay_0
        Ay_0 = Ay.copy()
        Ay = np.matmul(A, Ay)
        
        lambdaVector = Ay / Ay_0  # update lại lambda_vector 
        
        print('iter = %d, lambdaVector =' % (iter), end=' ')
        print(lambdaVector)
        
    return lambdaVector.max(), Ay / Ay[-1], iter 

### Ví dụ 1: SGK trang 107

In [147]:
A = np.array([[2, 3, 2], 
              [4, 3, 5], 
              [3, 2, 9]])

In [148]:
y = np.array([1, 1, 1]); eps = 1e-3

In [46]:
TH1(A.copy(), y.copy(), eps)

iter = 2, lambdaVector = [11.53846154 11.70895522 11.93567251]
iter = 3, lambdaVector = [11.76555556 11.79859783 11.86036257]
iter = 4, lambdaVector = [11.81679101 11.82622083 11.8417813 ]
iter = 5, lambdaVector = [11.83064542 11.83299913 11.8370021 ]
iter = 6, lambdaVector = [11.8341515  11.83475909 11.83578231]
iter = 7, lambdaVector = [11.83505277 11.83520796 11.83546996]


(11.8354699595324, array([0.43620241, 0.76339141, 1.        ]), 7)

- Tìm véc tơ riêng đầu tiên tương ứng với giá trị riêng trội   

In [150]:
modifiedTH1(A.copy(), y.copy(), 1e-5)

iter = 2, difVector = [-0.01518004 -0.01488492  0.        ]
iter = 3, difVector = [-0.00352486 -0.00400334  0.        ]
iter = 4, difVector = [-0.00092314 -0.00100489  0.        ]
iter = 5, difVector = [-0.00023441 -0.00025827  0.        ]
iter = 6, difVector = [-6.01130621e-05 -6.60034544e-05  0.00000000e+00]
iter = 7, difVector = [-1.53762856e-05 -1.68996254e-05  0.00000000e+00]
iter = 8, difVector = [-3.93621286e-06 -4.32495997e-06  0.00000000e+00]


(11.835369572866306, 8)

In [17]:
np.linalg.eig(A)

(array([11.83536254, -0.86464891,  3.02928637]),
 array([[-0.32758598, -0.75107583, -0.64630452],
        [-0.57330598,  0.65320185, -0.56423663],
        [-0.75100445,  0.0959815 ,  0.51373873]]))

In [151]:
A1 = np.array([[5, 3, 2], 
               [3, 4, 9], 
               [6, 7, 8]], dtype='float')
y1 = np.array([1, 1, 1], dtype='float'); eps = 1e-3

In [119]:
np.linalg.eig(A1.copy())

(array([16.23805894,  2.50643103, -1.74448997]),
 array([[-0.29403024, -0.81187861,  0.2417287 ],
        [-0.61199534,  0.55591067, -0.85246869],
        [-0.73417159,  0.17837166,  0.46353464]]))

In [11]:
TH1(A1.copy(), y1.copy(), eps)

iter = 1, lambdaVector =  [14.         17.6875     16.19047619]
iter = 2, lambdaVector =  [15.92142857 16.29681979 16.29705882]
iter = 3, lambdaVector =  [16.17900404 16.26279271 16.24002888]
iter = 4, lambdaVector =  [16.22990322 16.24018719 16.23912609]
iter = 5, lambdaVector =  [16.2366927  16.23856827 16.23814167]
iter = 6, lambdaVector =  [16.23785951 16.23811813 16.23808052]


(16.238118128142368, array([0.40049354, 0.83358573, 1.        ]), 6)

In [152]:
modifiedTH1(A1.copy(), y1.copy(), 1e-7)

iter = 2, difVector = [-9.49074811e-03 -1.22084567e-05  0.00000000e+00]
iter = 3, difVector = [-0.00151162  0.0011667   0.        ]
iter = 4, difVector = [-2.27609262e-04  5.44633897e-05  0.00000000e+00]
iter = 5, difVector = [-3.57408514e-05  2.18986868e-05  0.00000000e+00]
iter = 6, difVector = [-5.45113449e-06  1.93061164e-06  0.00000000e+00]
iter = 7, difVector = [-8.48460589e-07  4.53727711e-07  0.00000000e+00]
iter = 8, difVector = [-1.30206978e-07  5.33050866e-08  0.00000000e+00]
iter = 9, difVector = [-2.01795122e-08  1.00252853e-08  0.00000000e+00]


(16.238058980314275, 9)

In [144]:
def modifiedTH1(A, y, eps): 
    # hai giá trị lặp đầu tiên. 
    Ay_0 = np.matmul(A, y)
    Ay_0 = Ay_0 / Ay_0.max()
    Ay = np.matmul(A, Ay_0)
    Ay = Ay / Ay.max()
    iter =  1 
    
    difVector = Ay - Ay_0 
    
    while abs(difVector).max() >= eps: 
        # cập nhật lại số vòng lặp 
        iter += 1
        
        # cập nhật lại Ay và Ay_0
        Ay_0 = Ay.copy()
        Ay = np.matmul(A, Ay_0)
        Ay = Ay / Ay.max()
        
        difVector = Ay - Ay_0
        
        print('iter = %d, difVector =' % (iter), end=' ')
        print(difVector)
        
    # Tính trị riêng trội.
    Ay_0 = Ay.copy()
    Ay = np.matmul(A, Ay_0)
    lambdaVector = Ay / Ay_0
        
    return lambdaVector.max(), iter # lambdaVector.max(), Ay / Ay[-1], iter 

In [153]:
A3 = np.array([[1, 0], 
               [0, 2]], dtype='float')
y3 = np.array([1, 3], dtype='float'); eps = 1e-3

In [154]:
modifiedTH1(A3.copy(), y3.copy(), eps)  # TH này, các hệ số của lamdaVector không xấp xỉ bằng nhau, làm thế nào???

iter = 2, difVector = [-0.04166667  0.        ]
iter = 3, difVector = [-0.02083333  0.        ]
iter = 4, difVector = [-0.01041667  0.        ]
iter = 5, difVector = [-0.00520833  0.        ]
iter = 6, difVector = [-0.00260417  0.        ]
iter = 7, difVector = [-0.00130208  0.        ]
iter = 8, difVector = [-0.00065104  0.        ]


(2.0, 8)

## TH2: 

Ví dụ 1: Ma trận đối xứng, có trị riêng trội bội 2.

In [155]:
A = np.array([[3, -2, 4], 
              [-2, 6, 2], 
              [4, 2, 3]], dtype='float')
y = np.array([1, 1, 1], dtype='float'); eps = 1e-3

In [55]:
np.linalg.eig(A)

(array([ 7., -2.,  7.]),
 array([[ 0.74535599, -0.66666667, -0.14234692],
        [-0.2981424 , -0.33333333,  0.93490334],
        [ 0.59628479,  0.66666667,  0.32510475]]))

In [156]:
modifiedTH1(A, y, 1e-5)  # véc tơ riêng không chính xác. 

iter = 2, difVector = [-0.03156327 -0.02367245  0.        ]
iter = 3, difVector = [0.008895   0.00667125 0.        ]
iter = 4, difVector = [-0.00255132 -0.00191349  0.        ]
iter = 5, difVector = [0.00072814 0.0005461  0.        ]
iter = 6, difVector = [-0.00020811 -0.00015608  0.        ]
iter = 7, difVector = [5.94533764e-05 4.45900323e-05 0.00000000e+00]
iter = 8, difVector = [-1.69871198e-05 -1.27403399e-05  0.00000000e+00]
iter = 9, difVector = [4.85342681e-06 3.64007011e-06 0.00000000e+00]


(7.000005931979789, 9)

Ví dụ 2: Trị riêng trội bội 2, là 5.

In [157]:
A = np.array([[5, -2, 6, -1], 
              [0, 3, -8, 0], 
              [0, 0, 5, 4], 
              [0, 0, 0, 1]], dtype='float')
y = np.array([1, 1, 1, 1], dtype='float')

In [158]:
modifiedTH1(A.copy(), y.copy(), 1e-5)  # không hội tụ, thật là vl. 

iter = 2, difVector = [ 0.          0.17969074 -0.222164   -0.00869041]
iter = 3, difVector = [ 0.          0.15245161 -0.09154573 -0.00088861]
iter = 4, difVector = [ 0.          0.10753081 -0.04616747 -0.00011118]
iter = 5, difVector = [ 0.00000000e+00  7.57405216e-02 -2.67927694e-02 -1.56891647e-05]
iter = 6, difVector = [ 0.00000000e+00  5.47028136e-02 -1.71521787e-02 -2.38975150e-06]
iter = 7, difVector = [ 0.00000000e+00  4.06378793e-02 -1.17888749e-02 -3.83251314e-07]
iter = 8, difVector = [ 0.00000000e+00  3.09974255e-02 -8.54550303e-03 -6.37476774e-08]
iter = 9, difVector = [ 0.00000000e+00  2.42112592e-02 -6.45402891e-03 -1.08923172e-08]
iter = 10, difVector = [ 0.00000000e+00  1.93125836e-02 -5.03515235e-03 -1.89957659e-09]
iter = 11, difVector = [ 0.00000000e+00  1.56940860e-02 -4.03230583e-03 -3.36613501e-10]
iter = 12, difVector = [ 0.00000000e+00  1.29647942e-02 -3.29920819e-03 -6.04158928e-11]
iter = 13, difVector = [ 0.00000000e+00  1.08668207e-02 -2.74800826e-03 -1.09

(5.013196031764734, 380)

## TH3: Trị riêng thực bội 2 và trái dấu

- Đầu tiên, tính trị riêng trước. Lập luận như trên, công thức tính là: 
\begin{align}
\frac{(A^{2k+2}y)_j}{(A^{2k}y)_j} = \lambda_{1}^{2}, \qquad j = \overline{1, n}
\end{align}

- Sau đó, tính hai véc tơ riêng $x_1$ và $x_2$ theo công thức như sau:

In [159]:
def TH3(A, y, eps): 
    # hai giá trị lặp đầu tiên. 
    Ay_0 = np.matmul(A, y)
    Ay_0 = Ay_0 / abs(Ay_0).max()  # chú ý: lấy hệ số lớn nhất theo trị tuyệt đối.
    Ay_1 = np.matmul(A, Ay_0)
    Ay_1 = Ay_1 / abs(Ay_1).max()  # chú ý: lấy hệ số lớn nhất theo trị tuyệt đối.
    Ay_2 = np.matmul(A, Ay_1)
    Ay_2 = Ay_2 / abs(Ay_2).max()  # chú ý: lấy hệ số lớn nhất theo trị tuyệt đối.
    
    iter =  1 
    
    difVector = Ay_2 - Ay_0 
    
    print('iter = %d, difVector =' % (iter), end='  ')
    print(difVector)
    
    while abs(difVector).max() >= eps: 
        # cập nhật lại số vòng lặp 
        iter += 1
        
        # cập nhật lại 3 giá trị, mỗi giá trị nhảy lên 2 giá trị kế tiếp. 
        Ay_0 = Ay_2.copy()
        Ay_1 = np.matmul(A, Ay_2)
        Ay_1 = Ay_1 / abs(Ay_1).max()
        Ay_2 = np.matmul(A, Ay_1)
        Ay_2 = Ay_2 / abs(Ay_2).max()
        
        difVector = Ay_2 - Ay_0 
        
        print('iter = %d, difVector =' % (iter), end='  ')
        print(difVector)
        
    # Tính trị riêng trội.
    Ay_1 = Ay_2.copy()
    Ay_2 = np.matmul(A, Ay_2)
    lambdaVector = Ay_2 / Ay_1
        
#     lambda_square = lamdaVector.max()
    
#     lambda_1 = math.sqrt(lambda_square)
#     x1 = Ay_2 + lambda_1 * Ay_1  
    
#     lambda_2 = -math.sqrt(lambda_square)
#     x2 = Ay_2 + lambda_2 * Ay_1  
        
    return lambdaVector.max()

In [162]:
B = np.array([[13, 0, 0], 
              [0, -13, 0], 
              [0, 0, -2]], dtype='float')
b = np.array([1, 1, 1], dtype='float'); eps=1e-3

In [164]:
np.linalg.eig(B)

(array([ 13., -13.,  -2.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [163]:
TH3(B.copy(), b.copy(), eps)  # lỗi, lambdaVector chưa lấy căn đã ra kết quả ngon rồi. 

iter = 1, difVector =  [0.         0.         0.15020482]
iter = 2, difVector =  [0.         0.         0.00355514]
iter = 3, difVector =  [0.00000000e+00 0.00000000e+00 8.41454149e-05]


13.0

# Phương pháp xuống thang

In [18]:
A2 = np.diag((1, 2, 3))

In [20]:
TH1(A2, y, eps)

<ipython-input-11-fa490f9f38d9>:23: RuntimeWarning: invalid value encountered in true_divide
  lambda_vector = Ay_plus / Ay  # update lại lambda_vector


(1.0, array([          1,           0, -2133237029]), 81)