# 1. Gauss - Jordan 

# 2. Cholesky

In [2]:
import numpy as np

### 2.1. Hàm kiểm tra tính đối xứng của ma trận

In [3]:
def symmetryCheck(A): 
    n = len(A)
    
    for i in range(n): 
        for j in range(i): # không kiểm tra các phần tử đường chéo chính có bằng chính nó hay không.  
            if A[i][j] != A[j][i]: 
                return False 
    
    return True

### 2.2. Hàm tính Cholesky của ma trận

In [4]:
def Cholesky(A): 
    n = len(A)
    # Bước 1: Tính bình phương của phần tử đường chéo chính a_ii
    for i in range(n): 
        for k in range(i): 
            A[i][i] = A[i][i] - A[k][i]**2 # đoạn này có thể lấy inner product cho nhanh. 
            
        # Bước 3: Xét dấu của a_ii. 
        # Nếu a_ii <= 0 thì dừng thuật toán
        if A[i][i] <= 0: 
            return 'Matrix is not positive definite'
        
        # Ngược lại thì lấy căn của a_ii. 
        A[i][i] = np.sqrt(A[i][i]) 
            
        # Bước 4: Tính các phần tử a_ij, j = i + 1,..., n.
        for j in range(i + 1, n): 
            for k in range(i): 
                A[i][j] = A[i][j] - A[k][i] * A[k][j]
            
            A[i][j] = A[i][j] / A[i][i]
        
    # Bước 5: trả về ma trận tam dưới của A. Ta thu được ma trận L. 
    return np.tril(A.T)

### 2.3. Hàm tính nghịch đảo của ma trận tam giác dưới

In [5]:
def lowTriInverse(L):
    n = len(L)
    inv_L = np.zeros((n, n))
    
    for j in range(n): 
        inv_L[j][j] = 1 / L[j][j]
        
        for i in range(j + 1, n): 
            for k in range(j, i):
                inv_L[i][j] += L[i][k] * inv_L[k][j]
            
            inv_L[i][j] = -inv_L[i][j] / L[i][i]
            
    return inv_L 

### 2.4. Hàm tính nghịch đảo của một ma trận M = A^T.A

In [6]:
def posDeInverse(A): 
    M = np.matmul(A.T, A)  # Lúc này, M là ma trận đối xứng. 
        
    L = Cholesky(M) 
        
    if type(L) == str: 
        return 'Matrix is not positive definite.'
    else: 
        inv_L = lowTriInverse(L)  # Tính ma trận nghịch đảo của ma trận tam giác dưới L. 
    
        inv_M = np.matmul(inv_L.T, inv_L) # Nhân inv_L với chuyển vị của chính nó. 
        
        inv_A = np.matmul(inv_M, A.T)  # Tìm nghịch đảo của A
        
    return inv_A

### 2.5. Hàm thực thi chính 

In [7]:
def InvCholesky(A): 
    n = len(A)
    
    if symmetryCheck(A):
        L = Cholesky(A.copy())
        
        if type(L) == str: # Ma trận A không đối xứng, xác định dương => A có thể khả nghịch hoặc không. 
            inv_A = posDeInverse(A.copy())
        else:
            inv_L = lowTriInverse(L)  # Tính ma trận nghịch đảo của ma trận tam giác dưới L.
            
            inv_A = np.matmul(inv_L.T, inv_L)  # Nhân inv_L với chuyển vị của chính nó.
        
    else: 
        inv_A = posDeInverse(A.copy())                        
            
    return inv_A

Ví dụ 1: A là ma trận đối xứng, nhưng không xác định dương, nhưng vẫn khả nghịch.

In [8]:
A = np.array([[1, 3, -2], 
              [3, 4, -5], 
              [-2, -5, 3]], dtype='float')

In [9]:
InvCholesky(A.copy())

array([[-3.25,  0.25, -1.75],
       [ 0.25, -0.25, -0.25],
       [-1.75, -0.25, -1.25]])

In [10]:
np.linalg.inv(A.copy())

array([[-3.25,  0.25, -1.75],
       [ 0.25, -0.25, -0.25],
       [-1.75, -0.25, -1.25]])

Ví dụ 2: 

In [11]:
A1 = np.array([[50, 107, 36], 
              [25, 54, 20], 
              [31, 66, 21]], dtype='float')

In [12]:
InvCholesky(A1.copy())

array([[-185.99998026,  128.9999863 ,  195.99997921],
       [  94.99998992,  -65.999993  ,  -99.99998938],
       [ -23.99999746,   16.99999823,   24.99999732]])

In [13]:
np.linalg.inv(A1.copy())

array([[-186.,  129.,  196.],
       [  95.,  -66., -100.],
       [ -24.,   17.,   25.]])

Ví dụ 3:

In [14]:
A3 = np.array([[0, 0, 0, 1], 
              [1, 4, 1, 0], 
              [0, -1, 3, 0], 
              [3, 1, 0, 0]], dtype='float')

In [17]:
np.matmul(A3.T, A3)

array([[10.,  7.,  1.,  0.],
       [ 7., 18.,  1.,  0.],
       [ 1.,  1., 10.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [15]:
InvCholesky(A3)

array([[ 0.        , -0.08333333,  0.02777778,  0.36111111],
       [ 0.        ,  0.25      , -0.08333333, -0.08333333],
       [ 0.        ,  0.08333333,  0.30555556, -0.02777778],
       [ 1.        ,  0.        ,  0.        ,  0.        ]])

# 3. Viền quanh

Viền quanh được dùng trong trường hợp nào?

In [ ]:
def VienQuanh(A): 
    n = len(A)
    
    detA2 = 