In [34]:
import numpy as np 
import math

## Câu 2: Sử dụng Gauss Jordan

In [ ]:
Chú ý: 
- Ban đầu, chọn phần tử khử đầu tiên tại vị trí đang xét i, j.
- Tiếp, Chọn phần tử khử theo thứ tự 1, 2, 4, max, ...
- Chọn xong, kiểm tra xem phần tử khử có khác 0 hay không.

In [128]:
def rowExchange(Ab, n, k, i): 
    # Y tuong: di tung cot tu 0 den n, thuc hien trao doi hai phan tu tren hai hang thuoc cot do. 
    for j in range(n + 1): 
        Ab[k][j], Ab[i][j] = Ab[i][j], Ab[k][j]

In [129]:
def pivotSelection(Ab, m, i, j): 
    # Ưu tiên chọn phần tử khử là bội số của 2 theo thứ tự độ lớn tăng dần.
    for k in range(i, m): 
        if abs(Ab[k][j]) == 1: 
            return Ab[k][j], k
    for k in range(i, m): 
        if abs(Ab[k][j]) == 2: 
            return Ab[k][j], k
    for k in range(i, m): 
        if abs(Ab[k][j]) == 4: 
            return Ab[k][j], k
    for k in range(i, m): 
        if Ab[k][j] != 0 and Ab[k][j] % 2 == 0: 
            return Ab[k][j], k
    # Ưu tiên số hai là chọn phần tử khử là phần tử có trị tuyệt đối lớn nhất. 
    max = Ab[i][j]
    pivotRow = i
    for k in range(i + 1, m): 
        if abs(Ab[k][j]) > abs(max): 
            max = Ab[k][j]
            pivotRow = k
    
    return max, pivotRow

In [130]:
def printEliMatrix(Ab, m, n, ind, i, j):
    # In ra ma tran tam giac. 
    print('Elimination augmented matrix: ')
    for a in range(m): 
        for b in range(n + 1): 
            print('%.5f  ' %(Ab[a][b]), end='')
        print()

    print('index: ')
    print(ind)
    
    print('i = %d' %(i))
    print('j = %d' %(j))
    print()

In [131]:
def Sol(Ab, ind, m, n, rankA, rankAb): 
    if rankA == m and rankA == n:     # square and invertible. (square full rank)
        print('He co nghiem duy nhat.')
        x = solFinding(Ab, n, ind, rankA)
    elif rankA == m and rankA < n:    # short and wide (full row rank)
        print('He co vo so nghiem.')
        x = solFinding(Ab, n, ind, rankA)
    elif rankA < m and rankA == n:    # tall and thin. (full column rank) 
        if rankA == rankAb: 
            print('He co nghiem duy nhat.')
            x = solFinding(Ab, n, ind, rankA)
        else: 
            return 'He vo nghiem.'
    elif rankA < m and rankA < n:     # not full rank. 
        if rankA == rankAb: 
            print('He co vo so nghiem.')
            x = solFinding(Ab, n, ind, rankA)
        else: 
            return 'He vo nghiem.'
            
    return x 

In [132]:
def rankDeter(Ab, ind, m, n): 
    rankA = 0 
    for i in range(m):
        if ind[i] >= 0: 
            rankA += 1
    
    rankAb = rankA
    for i in range(m - 1, rankA - 1, -1): 
        if Ab[i][n] != 0: 
            rankAb = i + 1
            break 

    print('rankA = %d' %(rankA))
    print('rankAb = %d' %(rankAb))
    print()
    
    return rankA, rankAb

In [133]:
def solFinding(Ab, n, ind, rankA): 
    x = [0 for i in range(n)]
    row = rankA - 1

    for i in range(n): 
        if i not in ind: # neu cot thu i khong thuoc ind. 
            print('Bien thu %d la bien tu do. ' %(i + 1))
            x[i] = float(input('Ban muon dat bien tu do thu %d bang: ' %(i + 1)))

    # Bat dau qua trinh khu. 
    for i in range(n - 1, -1, -1): 
        if i in ind:   # neu bien thu i + 1 la bien khu (pivot variable).
            for j in range(n - 1, i, -1): 
                if j not in ind: 
                    Ab[row][n] -= Ab[row][j] * x[j]
            
            x[i] = Ab[row][n] / Ab[row][i]
            row -= 1
            
    return x  

In [134]:
def GaussJordan(Ab): 
    m = len(Ab)
    n = len(Ab[0]) - 1
    ind = [-1 for i in range(m)]   # ind[i] = j: phan tu khu thu i (hang i) o cot thu j.
    i, j = 0, 0 

    while i <= m - 1 and j <= n - 1:  # dung khi tim duoc het phan tu tru hoac di het cot.
        pivot, pivotRow = pivotSelection(Ab, m, i, j)
        print('pivot%d = %f' % (i + 1, pivot))
        
        if pivot == 0: 
            print('Cột %d không có phần tử khử.' % (j + 1), end='\n\n')
            j += 1
            flag = False 
        else: 
            ind[i] = j  # luu phan tru tru thu i o cot thu j. 
            flag = True 
            
            if pivotRow != i: 
                rowExchange(Ab, n, pivotRow, i)
                print('Row %d and row %d are exchanged!' % (pivotRow + 1, i + 1))
            else: 
                print('Không cần hoán đổi hàng.')
            
        if flag == True: 
            for k in range(m):
                if k != i: 
                    Ab[k][j] = Ab[k][j] / Ab[i][j]   
                
                    for t in range(j + 1, n + 1): 
                        Ab[k][t] = Ab[k][t] - Ab[k][j] * Ab[i][t]

            # dat lai cac he so bang 0 o cot thu j (cho de nhin).
            for t in range(i + 1, m): 
                Ab[t][j] = 0  
            for t in range(i): 
                Ab[t][j] = 0 

            i += 1 
            j += 1  
        
            print('Ma tran Ab sau khi khu phan tu tru thu %d o cot thu %d: ' % (i, j))
            for a in range(m): 
                for b in range(n + 1): 
                    print('%.5f     ' %(Ab[a][b]), end='')
                print()
            print()
          
    printEliMatrix(Ab, m, n, ind, i, j)
    
    rankA, rankAb = rankDeter(Ab, ind, m, n)

    x = Sol(Ab, ind, m, n, rankA, rankAb)
    
    if x == 'He vo nghiem.': 
        print(x)
    else: 
        print('Nghiem cua he Ax = b la: ')
        print(x)

In [137]:
Ab = [[0.003, 59.14, 59.17], 
     [5.291, -6.130, 46.68]]

In [138]:
GaussJordan(Ab.copy())

pivot1 = 5.291000
Row 2 and row 1 are exchanged!
Ma tran Ab sau khi khu phan tu tru thu 1 o cot thu 1: 
5.29100     -6.13000     46.68000     
0.00000     59.14348     59.14353     

pivot2 = 59.143476
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 2 o cot thu 2: 
5.29100     0.00000     52.81001     
0.00000     59.14348     59.14353     

Elimination augmented matrix: 
5.29100  0.00000  52.81001  
0.00000  59.14348  59.14353  
index: 
[0, 1]
i = 2
j = 2

rankA = 2
rankAb = 2

He co nghiem duy nhat.
Nghiem cua he Ax = b la: 
[9.981101091806607, 1.000000958686584]


In [23]:
Ab1 = [[1, 1, 0, 3, 4], 
      [2, 1, -1, 1, 1], 
      [3, -1, -1, 2, -3],
      [-1, 2, 3, -1, 4]]

if __name__ == '__main__':
    GaussJordan(Ab1.copy())               # [-1, 2, 0, 1]

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 1 o cot thu 1: 
1.00000     1.00000     0.00000     3.00000     4.00000     
0.00000     -1.00000     -1.00000     -5.00000     -7.00000     
0.00000     -4.00000     -1.00000     -7.00000     -15.00000     
0.00000     3.00000     3.00000     2.00000     8.00000     

pivot2 = -1.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 2 o cot thu 2: 
1.00000     0.00000     -1.00000     -2.00000     -3.00000     
0.00000     -1.00000     -1.00000     -5.00000     -7.00000     
0.00000     0.00000     3.00000     13.00000     13.00000     
0.00000     0.00000     0.00000     -13.00000     -13.00000     

pivot3 = 3.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 3 o cot thu 3: 
1.00000     0.00000     0.00000     2.33333     1.33333     
0.00000     -1.00000     0.00000     -0.66667     -2.66667     
0.00000     0.00000     3.00000     13.00000     13.00000     
0.000

In [24]:
Ab2 = [[1, 1, -3, 2, 6], 
       [1, -2, 0, -1, -6], 
       [0, 1, 1, 3, 16], 
       [2, -3, 2, 0, 6]]

if __name__ == '__main__':
    GaussJordan(Ab2.copy())               # [8, 6, 4, 2]

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 1 o cot thu 1: 
1.00000     1.00000     -3.00000     2.00000     6.00000     
0.00000     -3.00000     3.00000     -3.00000     -12.00000     
0.00000     1.00000     1.00000     3.00000     16.00000     
0.00000     -5.00000     8.00000     -4.00000     -6.00000     

pivot2 = 1.000000
Row 3 and row 2 are exchanged!
Ma tran Ab sau khi khu phan tu tru thu 2 o cot thu 2: 
1.00000     0.00000     -4.00000     -1.00000     -10.00000     
0.00000     1.00000     1.00000     3.00000     16.00000     
0.00000     0.00000     6.00000     6.00000     36.00000     
0.00000     0.00000     13.00000     11.00000     74.00000     

pivot3 = 6.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 3 o cot thu 3: 
1.00000     0.00000     0.00000     3.00000     14.00000     
0.00000     1.00000     0.00000     2.00000     10.00000     
0.00000     0.00000     6.00000     6.00000     36.00000     
0.0000

In [25]:
Ab7 = [[1, 1, -1, 1, -1, 2], 
      [2, 2, 1, -1, 1, 4], 
      [3, 1, -3, -2, 3, 8], 
      [4, 1, -1, 4, -5, 16], 
      [16, -1, 1, -1, -1, 32]]

if __name__ == '__main__':
    GaussJordan(Ab7.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 1 o cot thu 1: 
1.00000     1.00000     -1.00000     1.00000     -1.00000     2.00000     
0.00000     0.00000     3.00000     -3.00000     3.00000     0.00000     
0.00000     -2.00000     0.00000     -5.00000     6.00000     2.00000     
0.00000     -3.00000     3.00000     0.00000     -1.00000     8.00000     
0.00000     -17.00000     17.00000     -17.00000     15.00000     0.00000     

pivot2 = -2.000000
Row 3 and row 2 are exchanged!
Ma tran Ab sau khi khu phan tu tru thu 2 o cot thu 2: 
1.00000     0.00000     -1.00000     -1.50000     2.00000     3.00000     
0.00000     -2.00000     0.00000     -5.00000     6.00000     2.00000     
0.00000     0.00000     3.00000     -3.00000     3.00000     0.00000     
0.00000     0.00000     3.00000     7.50000     -10.00000     5.00000     
0.00000     0.00000     17.00000     25.50000     -36.00000     -17.00000     

pivot3 = 17.000000
Row 5 and row 3 are 

In [26]:
# TH khong the trao doi hang, phai tang bien j.
Ab = [[1, 2, 3, 2, 6, 9], 
      [2, 4, 4, 1, 5, 7], 
      [3, 6, 5, 2, 1, 4], 
      [2, 4, 1, 5, 3, 1], 
      [4, 8, 12, 5, 6, 2]]

if __name__ == '__main__':
    GaussJordan(Ab.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 1 o cot thu 1: 
1.00000     2.00000     3.00000     2.00000     6.00000     9.00000     
0.00000     0.00000     -2.00000     -3.00000     -7.00000     -11.00000     
0.00000     0.00000     -4.00000     -4.00000     -17.00000     -23.00000     
0.00000     0.00000     -5.00000     1.00000     -9.00000     -17.00000     
0.00000     0.00000     0.00000     -3.00000     -18.00000     -34.00000     

pivot2 = 0.000000
Cột 2 không có phần tử khử.

pivot2 = -2.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 2 o cot thu 3: 
1.00000     2.00000     0.00000     -2.50000     -4.50000     -7.50000     
0.00000     0.00000     -2.00000     -3.00000     -7.00000     -11.00000     
0.00000     0.00000     0.00000     2.00000     -3.00000     -1.00000     
0.00000     0.00000     0.00000     8.50000     8.50000     10.50000     
0.00000     0.00000     0.00000     -3.00000     -18.00000     -34.

In [30]:
Ab5 = [[1, 3, 0, 2, 1], 
      [0, 0, 1, 4, 6], 
      [1, 3, 1, 6, 7]]

if __name__ == '__main__':
    GaussJordan(Ab5.copy())    # Bien thu 2 va 4 la tu do. 

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 1 o cot thu 1: 
1.00000     3.00000     0.00000     2.00000     1.00000     
0.00000     0.00000     1.00000     4.00000     6.00000     
0.00000     0.00000     1.00000     4.00000     6.00000     

pivot2 = 0.000000
Cột 2 không có phần tử khử.

pivot2 = 1.000000
Không cần hoán đổi hàng.
Ma tran Ab sau khi khu phan tu tru thu 2 o cot thu 3: 
1.00000     3.00000     0.00000     2.00000     1.00000     
0.00000     0.00000     1.00000     4.00000     6.00000     
0.00000     0.00000     0.00000     0.00000     0.00000     

pivot3 = 0.000000
Cột 4 không có phần tử khử.

Elimination augmented matrix: 
1.00000  3.00000  0.00000  2.00000  1.00000  
0.00000  0.00000  1.00000  4.00000  6.00000  
0.00000  0.00000  0.00000  0.00000  0.00000  
index: 
[0, 2, -1]
i = 2
j = 4

rankA = 2
rankAb = 2

He co vo so nghiem.
Bien thu 2 la bien tu do. 
Ban muon dat bien tu do thu 2 bang: 2
Bien thu 4 la bien tu do. 
Ban muo

## Câu 3: Tính định thức của ma trận vuông dùng Gauss/Gauss Jordan

Câu hỏi: 
- Có cần chọn phần tử khử sao cho giảm sai số đi không? Có.

Chú ý: 
- Nếu trong quá trình khử có trao đổi hàng n lần thì định thức sẽ đổi dấu n lần.
- Nếu có một cột nào đó của ma trận vuông mà không có phần tử khử thì sẽ trả về det(A) = 0. Vì vậy, ta không cần mảng index để theo dõi các cột pivot nữa.
- Viết thêm hàm kiểm tra ma trận vuông nữa.
- In ma trận khử theo các cột thẳng nhau. 

In [52]:
def rowExchange2(A, n, k, i): 
    # Y tuong: di tung cot tu 0 den n, thuc hien trao doi hai phan tu tren hai hang thuoc cot do. 
    for j in range(n): 
        A[k][j], A[i][j] = A[i][j], A[k][j]

In [56]:
def printEliMatrix2(A, n):
    print('Elimination augmented matrix: ')
    for i in range(n): 
        for j in range(n): 
            print('%.5f  ' %(A[i][j]), end=' ')
        print()
    print()

In [47]:
def pivotSelection2(A, n, i): 
    # Ưu tiên chọn phần tử khử là bội số của 2 theo thứ tự độ lớn tăng dần.
    for k in range(i, n): 
        if abs(A[k][i]) == 1: 
            return A[k][i], k
    for k in range(i, n): 
        if abs(A[k][i]) == 2: 
            return A[k][i], k
    for k in range(i, n): 
        if abs(A[k][i]) == 4: 
            return A[k][i], k
    for k in range(i, n): 
        if A[k][i] != 0 and A[k][i] % 2 == 0: 
            return A[k][i], k
    # Ưu tiên số hai là chọn phần tử khử là phần tử có trị tuyệt đối lớn nhất. 
    max = A[i][i]
    pivotRow = i
    for k in range(i + 1, n): 
        if abs(A[k][i]) > abs(max): 
            max = A[k][i]
            pivotRow = k
    
    return max, pivotRow

In [62]:
def GaussDeter(A): 
    n = len(A)
    sign = 1
    
    for i in range(n): 
        pivot, pivotRow = pivotSelection2(A, n, i)
        print('pivot%d = %f' % (i + 1, pivot))
        
        if pivot == 0: 
            print('Cột %d không có phần tử khử.' % (j + 1), end='\n\n')
            flag = False 
        else: 
            flag = True 
            if pivotRow != i: 
                sign *= -1
                rowExchange2(A, n, pivotRow, i)
                print('Row %d and row %d are exchanged!' % (pivotRow + 1, i + 1))
                print('Update sign = %f' % (sign))
            else: 
                print('Không cần hoán đổi hàng.')
            
        if flag == False: 
            return 'detA = 0.0'
        else: 
            for row in range(i + 1, n):   # k là biến hàng
                A[row][i] = A[row][i] / A[i][i] 
                
                for col in range(i + 1, n): # t là biến cột
                    A[row][col] = A[row][col] - A[row][i] * A[i][col]
                
            # Đặt lại các phần tử dưới phần tử đường chéo chính A[i][i] = 0. 
            for row in range(i + 1, n): 
                A[row][i] = 0 

            print('Ma trận A sau khi khử phần tử trụ thứ %d: ' %(i + 1))
            for i in range(n): 
                for j in range(n): 
                    print('%.5f     ' %(A[i][j]), end='')
                print()
            print()
          
    printEliMatrix2(A, n)
    
    # Tính tích của các phần tử trên đường chéo chính của ma trận tam giác trên thu được ở trên. 
    detA = 1
    for i in range(n): 
        detA *= A[i][i]
    detA *= sign 
    
    return 'detA = %f' % (detA)

In [63]:
A = np.array([[1, 2, 3, 2, 6], 
              [2, 4, 4, 1, 5], 
              [3, 6, 5, 2, 1], 
              [2, 4, 1, 5, 3], 
              [4, 8, 12, 5, 6]], dtype='float')

In [64]:
GaussDeter(A.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     2.00000     3.00000     2.00000     6.00000     
0.00000     0.00000     -2.00000     -3.00000     -7.00000     
0.00000     0.00000     -4.00000     -4.00000     -17.00000     
0.00000     0.00000     -5.00000     1.00000     -9.00000     
0.00000     0.00000     0.00000     -3.00000     -18.00000     

pivot2 = 0.000000
Cột 5 không có phần tử khử.



'detA = 0.0'

In [65]:
A1 = np.array([[1, -1, 2, -1], 
               [2, -2, 3, -3], 
               [1, 1, 1, 0], 
               [1, -1, 4, 3]], dtype='float')

In [66]:
GaussDeter(A1.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     -1.00000     2.00000     -1.00000     
0.00000     0.00000     -1.00000     -1.00000     
0.00000     2.00000     -1.00000     1.00000     
0.00000     0.00000     2.00000     4.00000     

pivot2 = 2.000000
Row 3 and row 2 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     -1.00000     2.00000     -1.00000     
0.00000     2.00000     -1.00000     1.00000     
0.00000     0.00000     -1.00000     -1.00000     
0.00000     0.00000     2.00000     4.00000     

pivot3 = -1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     -1.00000     2.00000     -1.00000     
0.00000     2.00000     -1.00000     1.00000     
0.00000     0.00000     -1.00000     -1.00000     
0.00000     0.00000     0.00000     2.00000     

pivot4 = 2.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 4: 
1.00000     -1.00000   

'detA = 4.000000'

In [67]:
A2 = np.array([[1, 1, 0, 3], 
              [2, 1, -1, 1], 
              [3, -1, -1, 2],
              [-1, 2, 3, -1]], dtype='float')

In [68]:
GaussDeter(A2.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     1.00000     0.00000     3.00000     
0.00000     -1.00000     -1.00000     -5.00000     
0.00000     -4.00000     -1.00000     -7.00000     
0.00000     3.00000     3.00000     2.00000     

pivot2 = -1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     1.00000     0.00000     3.00000     
0.00000     -1.00000     -1.00000     -5.00000     
0.00000     0.00000     3.00000     13.00000     
0.00000     0.00000     0.00000     -13.00000     

pivot3 = 3.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     1.00000     0.00000     3.00000     
0.00000     -1.00000     -1.00000     -5.00000     
0.00000     0.00000     3.00000     13.00000     
0.00000     0.00000     0.00000     -13.00000     

pivot4 = -13.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 4: 
1.00000     1.00000     0.00000     3.00000     

'detA = 39.000000'

In [69]:
A3 = np.array([[4, 0, 0, 5], 
               [1, 7, 2, -5], 
               [3, 0, 0, 0], 
               [8, 3, 1, 7]], dtype='float')

In [70]:
GaussDeter(A3.copy())

pivot1 = 1.000000
Row 2 and row 1 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     7.00000     2.00000     -5.00000     
0.00000     -28.00000     -8.00000     25.00000     
0.00000     -21.00000     -6.00000     15.00000     
0.00000     -53.00000     -15.00000     47.00000     

pivot2 = -28.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     7.00000     2.00000     -5.00000     
0.00000     -28.00000     -8.00000     25.00000     
0.00000     0.00000     0.00000     -3.75000     
0.00000     0.00000     0.14286     -0.32143     

pivot3 = 0.142857
Row 4 and row 3 are exchanged!
Update sign = 1.000000
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     7.00000     2.00000     -5.00000     
0.00000     -28.00000     -8.00000     25.00000     
0.00000     0.00000     0.14286     -0.32143     
0.00000     0.00000     0.00000     -3.75000     

pivot4 = -3.750000
Không cần hoán đổi hàng.
Ma trận A sau khi khử

'detA = 15.000000'

In [71]:
np.linalg.det(A3.copy())

14.999999999999993

In [72]:
A4 = np.array([[3, 5, -6, 4], 
               [0, -2, 3, -3], 
               [0, 0, 1, 5], 
               [0, 0, 0, 3]], dtype='float')

In [73]:
GaussDeter(A4.copy())

pivot1 = 3.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
3.00000     5.00000     -6.00000     4.00000     
0.00000     -2.00000     3.00000     -3.00000     
0.00000     0.00000     1.00000     5.00000     
0.00000     0.00000     0.00000     3.00000     

pivot2 = -2.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 2: 
3.00000     5.00000     -6.00000     4.00000     
0.00000     -2.00000     3.00000     -3.00000     
0.00000     0.00000     1.00000     5.00000     
0.00000     0.00000     0.00000     3.00000     

pivot3 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 3: 
3.00000     5.00000     -6.00000     4.00000     
0.00000     -2.00000     3.00000     -3.00000     
0.00000     0.00000     1.00000     5.00000     
0.00000     0.00000     0.00000     3.00000     

pivot4 = 3.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 4: 
3.00000     5.00000     -6.00000     4.00000     
0.00000  

'detA = -18.000000'

In [74]:
np.linalg.det(A4.copy())

-17.999999999999996

In [75]:
A5 = np.array([[4, 0, -7, 3, -5], 
               [0, 0, 2, 0, 0], 
               [7, 3, -6, 4, -8], 
               [5, 0, 5, 2, -3], 
               [0, 0, 9, -1, 2]], dtype='float')

In [76]:
GaussDeter(A5.copy())

pivot1 = 4.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
4.00000     0.00000     -7.00000     3.00000     -5.00000     
0.00000     0.00000     2.00000     0.00000     0.00000     
0.00000     3.00000     6.25000     -1.25000     0.75000     
0.00000     0.00000     13.75000     -1.75000     3.25000     
0.00000     0.00000     9.00000     -1.00000     2.00000     

pivot2 = 3.000000
Row 3 and row 2 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 2: 
4.00000     0.00000     -7.00000     3.00000     -5.00000     
0.00000     3.00000     6.25000     -1.25000     0.75000     
0.00000     0.00000     2.00000     0.00000     0.00000     
0.00000     0.00000     13.75000     -1.75000     3.25000     
0.00000     0.00000     9.00000     -1.00000     2.00000     

pivot3 = 2.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 3: 
4.00000     0.00000     -7.00000     3.00000     -5.00000     
0.00000     3.00000     6.25

'detA = 6.000000'

In [77]:
np.linalg.det(A5.copy())

5.999999999999989

In [78]:
A6 = np.array([[6, 3, 2, 4, 0], 
               [9, 0, -4, 1, 0], 
               [8, -5, 6, 7, 1], 
               [2, 0, 0, 0, 0], 
               [4, 2, 3, 2, 0]], dtype='float')

In [79]:
GaussDeter(A6.copy())

pivot1 = 2.000000
Row 4 and row 1 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 1: 
2.00000     0.00000     0.00000     0.00000     0.00000     
0.00000     0.00000     -4.00000     1.00000     0.00000     
0.00000     -5.00000     6.00000     7.00000     1.00000     
0.00000     3.00000     2.00000     4.00000     0.00000     
0.00000     2.00000     3.00000     2.00000     0.00000     

pivot2 = 2.000000
Row 5 and row 2 are exchanged!
Update sign = 1.000000
Ma trận A sau khi khử phần tử trụ thứ 2: 
2.00000     0.00000     0.00000     0.00000     0.00000     
0.00000     2.00000     3.00000     2.00000     0.00000     
0.00000     0.00000     13.50000     12.00000     1.00000     
0.00000     0.00000     -2.50000     1.00000     0.00000     
0.00000     0.00000     -4.00000     1.00000     0.00000     

pivot3 = -4.000000
Row 5 and row 3 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 3: 
2.00000     0.00000     0.00000     0

'detA = 6.000000'

In [80]:
np.linalg.det(A6.copy())

6.000000000000013

In [81]:
A7 = np.array([[5, -7, 2, 2], 
               [0, 3, 0, -4], 
               [-5, -8, 0, 3], 
               [0, 5, 0, -6]], dtype='float')

In [82]:
GaussDeter(A7.copy())

pivot1 = 5.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
5.00000     -7.00000     2.00000     2.00000     
0.00000     3.00000     0.00000     -4.00000     
0.00000     -15.00000     2.00000     5.00000     
0.00000     5.00000     0.00000     -6.00000     

pivot2 = -15.000000
Row 3 and row 2 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 2: 
5.00000     -7.00000     2.00000     2.00000     
0.00000     -15.00000     2.00000     5.00000     
0.00000     0.00000     0.40000     -3.00000     
0.00000     0.00000     0.66667     -4.33333     

pivot3 = 0.666667
Row 4 and row 3 are exchanged!
Update sign = 1.000000
Ma trận A sau khi khử phần tử trụ thứ 3: 
5.00000     -7.00000     2.00000     2.00000     
0.00000     -15.00000     2.00000     5.00000     
0.00000     0.00000     0.66667     -4.33333     
0.00000     0.00000     0.00000     -0.40000     

pivot4 = -0.400000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ 

'detA = 20.000000'

In [83]:
np.linalg.det(A7.copy())

19.99999999999998

In [84]:
A8 = np.array([[2, -8, 6, 8], 
               [3, -9, 5, 10], 
               [-3, 0, 1, -2], 
               [1, -4, 0, 6]], dtype='float')

In [85]:
GaussDeter(A8.copy())

pivot1 = 1.000000
Row 4 and row 1 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     -4.00000     0.00000     6.00000     
0.00000     3.00000     5.00000     -8.00000     
0.00000     -12.00000     1.00000     16.00000     
0.00000     0.00000     6.00000     -4.00000     

pivot2 = -12.000000
Row 3 and row 2 are exchanged!
Update sign = 1.000000
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     -4.00000     0.00000     6.00000     
0.00000     -12.00000     1.00000     16.00000     
0.00000     0.00000     5.25000     -4.00000     
0.00000     0.00000     6.00000     -4.00000     

pivot3 = 6.000000
Row 4 and row 3 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     -4.00000     0.00000     6.00000     
0.00000     -12.00000     1.00000     16.00000     
0.00000     0.00000     6.00000     -4.00000     
0.00000     0.00000     0.00000     -0.50000     

pivot4 = -0.500000
Không cần hoán đổi hàng.
M

'detA = -36.000000'

In [86]:
np.linalg.det(A8.copy())

-36.000000000000014

In [87]:
A9 = np.array([[3, -1, 2, -5], 
               [0, 5, -3, -6], 
               [-6, 7, -7, 4], 
               [-5, -8, 0, 9]], dtype='float')

In [88]:
GaussDeter(A9.copy())

pivot1 = -6.000000
Row 3 and row 1 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 1: 
-6.00000     7.00000     -7.00000     4.00000     
0.00000     5.00000     -3.00000     -6.00000     
0.00000     2.50000     -1.50000     -3.00000     
0.00000     -13.83333     5.83333     5.66667     

pivot2 = -13.833333
Row 4 and row 2 are exchanged!
Update sign = 1.000000
Ma trận A sau khi khử phần tử trụ thứ 2: 
-6.00000     7.00000     -7.00000     4.00000     
0.00000     -13.83333     5.83333     5.66667     
0.00000     0.00000     -0.44578     -1.97590     
0.00000     0.00000     -0.89157     -3.95181     

pivot3 = -0.891566
Row 4 and row 3 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 3: 
-6.00000     7.00000     -7.00000     4.00000     
0.00000     -13.83333     5.83333     5.66667     
0.00000     0.00000     -0.89157     -3.95181     
0.00000     0.00000     0.00000     0.00000     

pivot4 = 0.000000
Cột 4 không có phần t

'detA = 0.0'

In [90]:
np.linalg.det(A9.copy())

0.0

In [91]:
A10 = np.array([[1, 3, -1, 0, -2], 
                [0, 2, -4, -2, -6], 
                [-2, -6, 2, 3, 10], 
                [1, 5, -6, 2, -3], 
                [0, 2, -4, 5, 9]], dtype='float')

In [92]:
GaussDeter(A10.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     3.00000     -1.00000     0.00000     -2.00000     
0.00000     2.00000     -4.00000     -2.00000     -6.00000     
0.00000     0.00000     0.00000     3.00000     6.00000     
0.00000     2.00000     -5.00000     2.00000     -1.00000     
0.00000     2.00000     -4.00000     5.00000     9.00000     

pivot2 = 2.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     3.00000     -1.00000     0.00000     -2.00000     
0.00000     2.00000     -4.00000     -2.00000     -6.00000     
0.00000     0.00000     0.00000     3.00000     6.00000     
0.00000     0.00000     -1.00000     4.00000     5.00000     
0.00000     0.00000     0.00000     7.00000     15.00000     

pivot3 = -1.000000
Row 4 and row 3 are exchanged!
Update sign = -1.000000
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     3.00000     -1.00000     0.00000     -2.00000     
0.00000     2.00000     

'detA = 6.000000'

In [93]:
np.linalg.det(A10.copy())

5.999999999999995

In [94]:
A11 = np.array([[1, -3, 1, -2], 
                [2, -5, -1, -2], 
                [0, -4, 5, 1], 
                [-3, 10, -6, 8]], dtype='float')

In [95]:
GaussDeter(A11.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     -3.00000     1.00000     -2.00000     
0.00000     1.00000     -3.00000     2.00000     
0.00000     -4.00000     5.00000     1.00000     
0.00000     1.00000     -3.00000     2.00000     

pivot2 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     -3.00000     1.00000     -2.00000     
0.00000     1.00000     -3.00000     2.00000     
0.00000     0.00000     -7.00000     9.00000     
0.00000     0.00000     0.00000     0.00000     

pivot3 = -7.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     -3.00000     1.00000     -2.00000     
0.00000     1.00000     -3.00000     2.00000     
0.00000     0.00000     -7.00000     9.00000     
0.00000     0.00000     0.00000     0.00000     

pivot4 = 0.000000
Cột 4 không có phần tử khử.



'detA = 0.0'

In [96]:
np.linalg.det(A11.copy())

9.763023722797423e-15

In [97]:
A12 = np.array([[8, 3, 3, 3, 3], 
                [3, 8, 3, 3, 3], 
                [3, 3, 8, 3, 3], 
                [3, 3, 3, 8, 3], 
                [3, 3, 3, 3, 8]], dtype='float')

In [98]:
GaussDeter(A12.copy())

pivot1 = 8.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
8.00000     3.00000     3.00000     3.00000     3.00000     
0.00000     6.87500     1.87500     1.87500     1.87500     
0.00000     1.87500     6.87500     1.87500     1.87500     
0.00000     1.87500     1.87500     6.87500     1.87500     
0.00000     1.87500     1.87500     1.87500     6.87500     

pivot2 = 6.875000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 2: 
8.00000     3.00000     3.00000     3.00000     3.00000     
0.00000     6.87500     1.87500     1.87500     1.87500     
0.00000     0.00000     6.36364     1.36364     1.36364     
0.00000     0.00000     1.36364     6.36364     1.36364     
0.00000     0.00000     1.36364     1.36364     6.36364     

pivot3 = 6.363636
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 3: 
8.00000     3.00000     3.00000     3.00000     3.00000     
0.00000     6.87500     1.87500     1.87500     1.87500     
0.00000    

'detA = 12500.000000'

In [99]:
np.linalg.det(A12.copy())

12500.0

In [100]:
A13 = np.array([[1, 1, 1, 1, 1], 
                [1, 2, 2, 2, 2], 
                [1, 2, 3, 3, 3], 
                [1, 2, 3, 4, 4], 
                [1, 2, 3, 4, 5]], dtype='float')

In [101]:
GaussDeter(A13.copy())

pivot1 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     1.00000     1.00000     1.00000     1.00000     
0.00000     1.00000     1.00000     1.00000     1.00000     
0.00000     1.00000     2.00000     2.00000     2.00000     
0.00000     1.00000     2.00000     3.00000     3.00000     
0.00000     1.00000     2.00000     3.00000     4.00000     

pivot2 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     1.00000     1.00000     1.00000     1.00000     
0.00000     1.00000     1.00000     1.00000     1.00000     
0.00000     0.00000     1.00000     1.00000     1.00000     
0.00000     0.00000     1.00000     2.00000     2.00000     
0.00000     0.00000     1.00000     2.00000     3.00000     

pivot3 = 1.000000
Không cần hoán đổi hàng.
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     1.00000     1.00000     1.00000     1.00000     
0.00000     1.00000     1.00000     1.00000     1.00000     
0.00000    

'detA = 1.000000'

In [102]:
np.linalg.det(A13.copy())

1.0

In [ ]:
def GaussDetermt(A): 
    n = len(A)
    sign = 1
    
    for i in range(n): 
        flag = True 
        if A[i][i] != 0: 
            print('Không cần hoán đổi.')
        else: 
            print('Cần hoán đổi.')
            
            # Tìm hàng để hoán đổi. 
            for k in range(i + 1, n): 
                if A[k][i] != 0: 
                    rowExchange(A, n, k, i)
                    sign *= -1 
                    
                    print('Hàng %d và hàng %d đã được hoán đổi!' % (k + 1, i + 1))
                    break 
            else: 
                print('Cột thứ %d không có phần tử hoán đổi được.' % (i + 1))
                flag = False
        
        # Kiểm tra xem cột thứ i có phần tử pivot không. 
        if flag == False: 
            return 'detA = 0.0'
        else: 
            for row in range(i + 1, n):   # k là biến hàng
                A[row][i] = A[row][i] / A[i][i] 
                
                for col in range(i + 1, n): # t là biến cột
                    A[row][col] = A[row][col] - A[row][i] * A[i][col]
                
            # Đặt lại các phần tử dưới phần tử đường chéo chính A[i][i] = 0. 
            for row in range(i + 1, n): 
                A[row][i] = 0 

            print('Ma trận A sau khi khử phần tử trụ thứ %d: ' %(i + 1))
            for i in range(n): 
                for j in range(n): 
                    print('%.5f     ' %(A[i][j]), end='')
                print()
            print()
          
    printEliMatrix(A, n)

    # Tính tích của các phần tử trên đường chéo chính của ma trận tam giác trên thu được ở trên. 
    detA = 1
    for i in range(n): 
        detA *= A[i][i]
    detA *= sign 
    
    return 'detA = %f' % (detA)

Ví dụ 1: Ma trận A có cột không thể trao đổi hàng => trả về detA = 0.

In [61]:
A = np.array([[1, 2, 3, 2, 6], 
              [2, 4, 4, 1, 5], 
              [3, 6, 5, 2, 1], 
              [2, 4, 1, 5, 3], 
              [4, 8, 12, 5, 6]], dtype='float')

In [62]:
GaussDeter(A.copy())

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     2.00000     3.00000     2.00000     6.00000     
0.00000     0.00000     -2.00000     -3.00000     -7.00000     
0.00000     0.00000     -4.00000     -4.00000     -17.00000     
0.00000     0.00000     -5.00000     1.00000     -9.00000     
0.00000     0.00000     0.00000     -3.00000     -18.00000     

Cần hoán đổi.
Cột thứ 2 không có phần tử hoán đổi được.


'detA = 0.0'

Kiểm chứng với hàm của numpy: 

In [49]:
np.linalg.det(A.copy())

0.0

Ví dụ 2: Trường hợp ma trận A có trao đổi hàng, và định thức đổi dấu.

In [50]:
A1 = np.array([[1, -1, 2, -1], 
               [2, -2, 3, -3], 
               [1, 1, 1, 0], 
               [1, -1, 4, 3]], dtype='float')

In [51]:
GaussDeter(A1.copy())

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     -1.00000     2.00000     -1.00000     
0.00000     0.00000     -1.00000     -1.00000     
0.00000     2.00000     -1.00000     1.00000     
0.00000     0.00000     2.00000     4.00000     

Cần hoán đổi.
Hàng 3 và hàng 2 đã được hoán đổi!
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     -1.00000     2.00000     -1.00000     
0.00000     2.00000     -1.00000     1.00000     
0.00000     0.00000     -1.00000     -1.00000     
0.00000     0.00000     2.00000     4.00000     

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     -1.00000     2.00000     -1.00000     
0.00000     2.00000     -1.00000     1.00000     
0.00000     0.00000     -1.00000     -1.00000     
0.00000     0.00000     0.00000     2.00000     

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 4: 
1.00000     -1.00000     2.00000     -1.00000     
0.00000     2.00000     -1.00000     1.00000     
0.00000     0.00

'detA = 4.000000'

Kiểm chứng với hàm numpy:

In [52]:
np.linalg.det(A1.copy())

4.000000000000001

Ví dụ 3: Không cần hoán đổi hàng => Định thức không đổi dấu.

In [57]:
A2 = np.array([[1, 1, 0, 3], 
              [2, 1, -1, 1], 
              [3, -1, -1, 2],
              [-1, 2, 3, -1]], dtype='float')

In [58]:
GaussDeter(A2.copy())

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 1: 
1.00000     1.00000     0.00000     3.00000     
0.00000     -1.00000     -1.00000     -5.00000     
0.00000     -4.00000     -1.00000     -7.00000     
0.00000     3.00000     3.00000     2.00000     

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 2: 
1.00000     1.00000     0.00000     3.00000     
0.00000     -1.00000     -1.00000     -5.00000     
0.00000     0.00000     3.00000     13.00000     
0.00000     0.00000     0.00000     -13.00000     

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 3: 
1.00000     1.00000     0.00000     3.00000     
0.00000     -1.00000     -1.00000     -5.00000     
0.00000     0.00000     3.00000     13.00000     
0.00000     0.00000     0.00000     -13.00000     

Không cần hoán đổi.
Ma trận A sau khi khử phần tử trụ thứ 4: 
1.00000     1.00000     0.00000     3.00000     
0.00000     -1.00000     -1.00000     -5.00000     
0.00000     0.00000     3.00000     13.000

'detA = 39.000000'

Kiểm chứng kết quả trên với hàm det của numpy: 

In [59]:
np.linalg.det(A2.copy())

38.99999999999999

Ví dụ 4: Trường hợp trao đổi hàng nhiều lần => định thức đổi dấu nhiều lần. 

## Câu 4: 

Chú ý: 
- Các phần tử ngoài đường chéo chính được lặp về dần 0, vì vậy vẫn phải cần sai số để dừng vòng lặp.
- Cần chứng minh được sự hội tụ của thuật toán.

In [105]:
def JacobiEigenAlgo(A): # chú ý là ma trận A phải là ma trận đối xứng.
    n = len(A)
    flag = True
    iter = 0
    
    S = np.identity(n)
    
    # Tìm phần tử có trị tuyệt đối lớn nhất ngoài đường chéo chính từ D, ta chỉ search ở nửa trên của D.
    while flag == True:    
        iter += 1
        flag = False
        row, col = 0, 0
        max = 0 
        for i in range(n): 
            for j in range(i + 1, n): 
                if abs(A[i][j]) > max: 
                    max = abs(A[i][j])
                    row, col = i, j
                    
        # Tìm góc quay. 
        if A[row][row] == A[col][col]: 
            if A[row][col] > 0: 
                theta = math.pi / 4
            else: 
                theta = -math.pi / 4
        else: 
            theta = 0.5 * math.atan(2 * A[row][col] / (A[row][row] - A[col][col]))
    
        # Tính ma trận S1 là ma trận quay tương ứng với góc quay theta ở trên. 
        S1 = np.identity(n)
        S1[row][row], S1[col][col] = math.cos(theta), math.cos(theta)
        S1[row][col], S1[col][row] = -math.sin(theta), math.sin(theta)
    
        A = np.matmul(S1.T, np.matmul(A, S1))
        S = np.matmul(S, S1)
        
        # Đặt lại phần tử D[i][j] = 0, vì nếu không sẽ bị xấp xỉ bằng 0. 
        A[row][col], A[col][row] = 0.0, 0.0
        
        # Kiểm tra xem còn phần tử nào lớn hơn 0 không. 
        for i in range(n): 
            for j in range(i + 1, n): 
                if abs(A[i][j]) > 1e-10: 
                    flag = True 
                    break 
            if flag == True: 
                break 
        
        print('iter %d: ' % (iter))
        print('eigenvalues: ')
        for i in range(n): 
            for j in range(n): 
                print('%.10f  ' % (A[i][j]), end=' ')
            print()
        print()
        
        print('eigenvectors: ')
        for i in range(n): 
            for j in range(n): 
                print('%.10f  ' % (S[i][j]), end=' ')
            print()
        print()
        
    return np.diag(A), S

In [55]:
A = np.array([[4, -30, 60, -35], 
              [-30, 300, -675, 420], 
              [60, -675, 1620, -1050], 
              [-35, 420, -1050, 700]], dtype='float')

In [56]:
JacobiEigenAlgo(A.copy())

iter 1: 
eigenvalues: 
4.0000000000   -30.0000000000   69.3723680938   3.5319321985   
-30.0000000000   300.0000000000   -794.8015568895   -17.7619020953   
69.3723680938   -794.8015568895   2306.3420083029   0.0000000000   
3.5319321985   -17.7619020953   0.0000000000   13.6579916971   

eigenvectors: 
1.0000000000   0.0000000000   0.0000000000   0.0000000000   
0.0000000000   1.0000000000   0.0000000000   0.0000000000   
0.0000000000   0.0000000000   0.8370413386   0.5471396508   
0.0000000000   0.0000000000   -0.5471396508   0.8370413386   

iter 2: 
eigenvalues: 
4.0000000000   -5.5240022975   75.3791141734   3.5319321985   
-5.5240022975   23.3032069145   0.0000000000   -16.7744606195   
75.3791141734   0.0000000000   2583.0388013884   5.8397463102   
3.5319321985   -16.7744606195   5.8397463102   13.6579916971   

eigenvectors: 
1.0000000000   0.0000000000   0.0000000000   0.0000000000   
0.0000000000   0.9444067718   -0.3287793322   0.0000000000   
0.0000000000   0.2752018924   

In [37]:
np.linalg.eig(A.copy())

(array([2.58525381e+03, 3.71014914e+01, 1.66642861e-01, 1.47805484e+00]),
 array([[ 0.02919332, -0.17918629,  0.79260829, -0.5820757 ],
        [-0.32871206,  0.74191779,  0.45192312,  0.37050219],
        [ 0.79141115, -0.10022814,  0.3224164 ,  0.50957863],
        [-0.51455275, -0.63828253,  0.25216117,  0.51404827]]))

Ví dụ 2: 

In [41]:
A1 = np.array([[6, -2, -1],
               [-2, 6, -1], 
               [-1, -1, 5]], dtype='float')

In [42]:
JacobiEigenAlgo(A1.copy())

iter 1: 
eigenvalues: 
8.0000000000   0.0000000000   0.0000000000   
0.0000000000   4.0000000000   -1.4142135624   
0.0000000000   -1.4142135624   5.0000000000   

eigenvectors: 
0.7071067812   0.7071067812   0.0000000000   
-0.7071067812   0.7071067812   0.0000000000   
0.0000000000   0.0000000000   1.0000000000   

iter 2: 
eigenvalues: 
8.0000000000   0.0000000000   0.0000000000   
0.0000000000   3.0000000000   0.0000000000   
0.0000000000   0.0000000000   6.0000000000   

eigenvectors: 
0.7071067812   0.5773502692   -0.4082482905   
-0.7071067812   0.5773502692   -0.4082482905   
0.0000000000   0.5773502692   0.8164965809   



In [40]:
np.linalg.eig(A1.copy())

(array([3., 8., 6.]),
 array([[ 5.77350269e-01,  7.07106781e-01, -4.08248290e-01],
        [ 5.77350269e-01, -7.07106781e-01, -4.08248290e-01],
        [ 5.77350269e-01, -2.23967696e-17,  8.16496581e-01]]))

Ví dụ 3: Trường hợp có trị riêng bội 2:

In [46]:
A2 = np.array([[3, -2, 4], 
               [-2, 6, 2], 
               [4, 2, 3]], dtype='float')

In [44]:
JacobiEigenAlgo(A2.copy())

iter 1: 
eigenvalues: 
7.0000000000   0.0000000000   0.0000000000   
0.0000000000   6.0000000000   2.8284271247   
0.0000000000   2.8284271247   -1.0000000000   

eigenvectors: 
0.7071067812   0.0000000000   -0.7071067812   
0.0000000000   1.0000000000   0.0000000000   
0.7071067812   0.0000000000   0.7071067812   

iter 2: 
eigenvalues: 
7.0000000000   0.0000000000   0.0000000000   
0.0000000000   7.0000000000   0.0000000000   
0.0000000000   0.0000000000   -2.0000000000   

eigenvectors: 
0.7071067812   -0.2357022604   -0.6666666667   
0.0000000000   0.9428090416   -0.3333333333   
0.7071067812   0.2357022604   0.6666666667   



In [47]:
np.linalg.eig(A2.copy())

(array([ 7., -2.,  7.]),
 array([[ 0.74535599, -0.66666667, -0.14234692],
        [-0.2981424 , -0.33333333,  0.93490334],
        [ 0.59628479,  0.66666667,  0.32510475]]))

hmm... vd3 thì kết quả của lệnh eig là sai nếu so với trong sách. còn kq của thuật toán của mình là đúng.

Ví dụ 4: 

In [48]:
A3 = np.array([[80, 100, 40], 
               [100, 170, 140], 
               [40, 140, 200]], dtype='float')

In [49]:
JacobiEigenAlgo(A3.copy())

iter 1: 
eigenvalues: 
80.0000000000   47.6466421019   96.5908768798   
47.6466421019   44.1987215967   0.0000000000   
96.5908768798   0.0000000000   325.8012784033   

eigenvectors: 
1.0000000000   0.0000000000   0.0000000000   
0.0000000000   0.7438189039   0.6683812072   
0.0000000000   -0.6683812072   0.7438189039   

iter 2: 
eigenvalues: 
46.5856859419   45.0284370154   0.0000000000   
45.0284370154   44.1987215967   15.5769818494   
0.0000000000   15.5769818494   359.2155924614   

eigenvectors: 
0.9450495361   0.0000000000   0.3269271697   
-0.2185119764   0.7438189039   0.6316533498   
-0.2431746090   -0.6683812072   0.7029457101   

iter 3: 
eigenvalues: 
90.4364546760   0.0000000000   10.8676898868   
0.0000000000   0.3479528626   11.1595555494   
10.8676898868   11.1595555494   359.2155924614   

eigenvectors: 
0.6770459706   -0.6593385924   0.3269271697   
0.3623998985   0.6853322984   0.6316533498   
-0.6405271792   -0.3091799822   0.7029457101   

iter 4: 
eigenvalues: 

In [ ]:
Có vấn đề là so với kq trong sách thì 90 và 0 có véc tơ riêng được đổi dấu, nhưng vt riêng 360 vẫn giữ nguyên dấu. 

In [50]:
np.linalg.eig(A3.copy())

(array([ 3.60000000e+02, -3.18981901e-14,  9.00000000e+01]),
 array([[-0.33333333, -0.66666667, -0.66666667],
        [-0.66666667,  0.66666667, -0.33333333],
        [-0.66666667, -0.33333333,  0.66666667]]))

### - Ứng dụng vào lưu ma trận sử dụng ô nhớ nhỏ nhất.

Đầu tiên, phải tìm được SVD của A bằng thuật toán Jacobi.

In [43]:
A = np.array([[4, 11, 14], 
              [8, 7, -2]], dtype='float')

In [81]:
square_Sigma1, V = JacobiEigenAlgo(np.matmul(A.T, A))

iter 1: 
eigenvalues: 
80.0000000000   47.6466421019   96.5908768798   
47.6466421019   44.1987215967   0.0000000000   
96.5908768798   0.0000000000   325.8012784033   

eigenvectors: 
1.0000000000   0.0000000000   0.0000000000   
0.0000000000   0.7438189039   0.6683812072   
0.0000000000   -0.6683812072   0.7438189039   

iter 2: 
eigenvalues: 
46.5856859419   45.0284370154   0.0000000000   
45.0284370154   44.1987215967   15.5769818494   
0.0000000000   15.5769818494   359.2155924614   

eigenvectors: 
0.9450495361   0.0000000000   0.3269271697   
-0.2185119764   0.7438189039   0.6316533498   
-0.2431746090   -0.6683812072   0.7029457101   

iter 3: 
eigenvalues: 
90.4364546760   0.0000000000   10.8676898868   
0.0000000000   0.3479528626   11.1595555494   
10.8676898868   11.1595555494   359.2155924614   

eigenvectors: 
0.6770459706   -0.6593385924   0.3269271697   
0.3623998985   0.6853322984   0.6316533498   
-0.6405271792   -0.3091799822   0.7029457101   

iter 4: 
eigenvalues: 

In [45]:
print(square_Sigma1)

[9.00000000e+01 1.86386605e-15 3.60000000e+02]


In [46]:
print(V)

[[ 0.66666667 -0.66666667  0.33333333]
 [ 0.33333333  0.66666667  0.66666667]
 [-0.66666667 -0.33333333  0.66666667]]


In [26]:
square_Sigma2, U = JacobiEigenAlgo(np.matmul(A, A.T))

iter 1: 
eigenvalues: 
360.0000000000   0.0000000000   
0.0000000000   90.0000000000   

eigenvectors: 
0.9486832981   -0.3162277660   
0.3162277660   0.9486832981   



In [27]:
print(square_Sigma2)

[360.  90.]


In [28]:
print(U)

[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]


Bây giờ, cần sắp xếp lại square_Sigma và V theo thứ tự độ lớn giảm dần. 

In [106]:
def bubbleSort(numbers, arrays): 
    n = len(numbers)
    
    nums = numbers.copy()
    array = arrays.copy()
    
    for i in range(n): 
        for j in range(n - i - 1): 
            if nums[j] < nums[j + 1]: 
                nums[j], nums[j + 1] = nums[j + 1], nums[j]
                array[:, [j, j + 1]] = array[:, [j + 1, j]]
                
    return nums, array

In [82]:
square_Sigma1, V = bubbleSort(square_Sigma1, V)

In [83]:
square_Sigma1

array([3.60000000e+02, 9.00000000e+01, 1.86386605e-15])

In [84]:
V

array([[ 0.33333333,  0.66666667, -0.66666667],
       [ 0.66666667,  0.33333333,  0.66666667],
       [ 0.66666667, -0.66666667, -0.33333333]])

In [85]:
square_Sigma2, U = bubbleSort(square_Sigma2, U)

In [86]:
square_Sigma2

array([360.,  90.])

In [87]:
U

array([[ 0.9486833 , -0.31622777],
       [ 0.31622777,  0.9486833 ]])

### Công thức tìm số k 

In [107]:
def findK(square_Sigma): 
    for k in range(len(square_Sigma)): 
        print('k = %d, r = %f' % (k, np.sum(square_Sigma[:k + 1]) / np.sum(square_Sigma)))
        if np.sum(square_Sigma[:k + 1]) >= 0.98**2 * np.sum(square_Sigma): 
            return k

In [108]:
findK(square_Sigma2)

NameError: name 'square_Sigma2' is not defined

In [120]:
def matrixStoring(A): 
    square_Sigma1, V = JacobiEigenAlgo(np.matmul(A.T, A))
    square_Sigma2, U = JacobiEigenAlgo(np.matmul(A, A.T))
    
    square_Sigma1, V = bubbleSort(square_Sigma1, V)
    square_Sigma2, U = bubbleSort(square_Sigma2, U)
    
    print('Sigma1: ')
    print(np.sqrt(square_Sigma1), end='\n\n')
    
    print('V: ')
    print(V, end='\n\n')
    
    print('square_Sigma2: ')
    print(np.sqrt(square_Sigma2), end='\n\n')
    
    print('U: ')
    print(U, end='\n\n')
    
    k = findK(square_Sigma1)
    
    print(k)
    
    return U, np.sqrt(square_Sigma1), V

In [110]:
A1 = np.array([[6, -8, -4, 5, -4], 
               [2, 7, -5, -6, 4], 
               [0, -1, -8, 2, 2], 
               [-1, -2, 4, 4, -8]], dtype='float')

In [111]:
matrixStoring(A1)

iter 1: 
eigenvalues: 
41.0000000000   -33.6277315857   -38.0000000000   -9.4432869490   -8.0000000000   
-33.6277315857   193.3416218956   -8.6568675623   0.0000000000   102.8699259710   
-38.0000000000   -8.6568675623   121.0000000000   5.8359784105   -52.0000000000   
-9.4432869490   0.0000000000   5.8359784105   5.6583781044   -8.8192023860   
-8.0000000000   102.8699259710   -52.0000000000   -8.8192023860   100.0000000000   

eigenvectors: 
1.0000000000   0.0000000000   0.0000000000   0.0000000000   0.0000000000   
0.0000000000   0.7736732733   0.0000000000   0.6335847742   0.0000000000   
0.0000000000   0.0000000000   1.0000000000   0.0000000000   0.0000000000   
0.0000000000   -0.6335847742   0.0000000000   0.7736732733   0.0000000000   
0.0000000000   0.0000000000   0.0000000000   0.0000000000   1.0000000000   

iter 2: 
eigenvalues: 
41.0000000000   -32.6003354113   -38.0000000000   -9.4432869490   11.4909730950   
-32.6003354113   259.6326906409   -35.4444086459   -4.77722687

-0.4083810867   -0.5181977165   -0.1422204832   0.7360283192   0.0522653042   
-0.0118755520   0.5471763139   -0.1882580881   0.2880982145   0.7628993144   

iter 12: 
eigenvalues: 
21.7894140653   2.5904893434   0.0000000000   -0.8802740631   -2.4882163192   
2.5904893434   270.8306956381   -0.3625371167   0.0000000000   1.4920847673   
0.0000000000   -0.3625371167   147.8297997830   -1.7550709251   -0.7408007809   
-0.8802740631   0.0000000000   -1.7550709251   0.0568081614   0.0233098532   
-2.4882163192   1.4920847673   -0.7408007809   0.0233098532   20.4932823522   

eigenvectors: 
0.8431779577   -0.1093177485   -0.3858746230   0.3357753618   -0.1243231405   
-0.0636624074   0.6111593787   0.2874594123   0.4847787948   -0.5520760075   
0.3387010111   -0.2158773998   0.8462644988   0.1658498074   0.3082349960   
-0.4122882378   -0.5181977165   -0.1304614380   0.7360283192   0.0522653042   
-0.0172645202   0.5471763139   -0.1878405515   0.2880982145   0.7628993144   

iter 13: 
eige

0.6330986165   0.0689136802   0.7682258933   0.0653148008   
-0.3404011324   -0.5347745470   0.2667794780   0.7259283457   

iter 7: 
eigenvalues: 
147.8524206138   -0.0116984271   -0.0578030762   -0.4220559827   
-0.0116984271   270.8672951119   -0.0747605581   0.0000000000   
-0.0578030762   -0.0747605581   21.4356381826   -2.5700102656   
-0.4220559827   0.0000000000   -2.5700102656   20.8446460917   

eigenvectors: 
0.6519717151   -0.5722189125   -0.4911610487   0.0791152520   
0.2413422744   0.6347460921   -0.3121193861   0.6644040894   
0.6330986165   0.0706969052   0.7682258933   0.0633803292   
-0.3404011324   -0.5144558896   0.2667794780   0.7404666885   

iter 8: 
eigenvalues: 
147.8524206138   -0.0116984271   0.2377330104   -0.3534904014   
-0.0116984271   270.8672951119   -0.0558012823   -0.0497529692   
0.2377330104   -0.0558012823   23.7270844786   0.0000000000   
-0.3534904014   -0.0497529692   0.0000000000   18.5531997957   

eigenvectors: 
0.6519717151   -0.5722189125 

In [116]:
U, Sigma, V = np.linalg.svd(A1.copy())

In [117]:
Sigma

array([16.45804723, 12.15951649,  4.8709975 ,  4.30722921])

In [118]:
U

array([[ 0.57213333, -0.65184302,  0.4206649 , -0.26609241],
       [-0.63481885, -0.23932025,  0.67540574,  0.2890639 ],
       [-0.07040672, -0.63259215, -0.53009891,  0.56023675],
       [ 0.5145011 ,  0.34300679,  0.29302436,  0.72922677]])

In [119]:
V

array([[ 0.10017356, -0.60635347,  0.21307626,  0.52173691, -0.55198717],
       [-0.38921823,  0.28669569,  0.84187046, -0.1411611 , -0.19401656],
       [ 0.73532711,  0.26823482,  0.07251089, -0.37717331, -0.48972092],
       [-0.40574888,  0.49532916, -0.45178389,  0.22579136, -0.5787283 ],
       [ 0.36487849,  0.48253513,  0.19101341,  0.71737207,  0.28794915]])

In [120]:
np.matmul(np.matmul(U, Sigma), V)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [121]:
np.linalg.eig(np.matmul(A1.T, A1))

(array([ 2.70867319e+02,  1.47853841e+02, -8.92902422e-15,  2.37266167e+01,
         1.85522235e+01]),
 array([[-0.10017356, -0.38921823,  0.36487849, -0.73532711,  0.40574888],
        [ 0.60635347,  0.28669569,  0.48253513, -0.26823482, -0.49532916],
        [-0.21307626,  0.84187046,  0.19101341, -0.07251089,  0.45178389],
        [-0.52173691, -0.1411611 ,  0.71737207,  0.37717331, -0.22579136],
        [ 0.55198717, -0.19401656,  0.28794915,  0.48972092,  0.5787283 ]]))

In [113]:
A2 = np.array([[-18, 13, -4, 4], 
               [2, 19, -4, 12], 
               [-14, 11, -12, 8], 
               [-2, 21, 4, 8]], dtype='float')

In [114]:
matrixStoring(A2.copy())

iter 1: 
eigenvalues: 
528.0000000000   -429.3250516800   224.0000000000   17.8885438200   
-429.3250516800   1360.0000000000   -214.6625258400   0.0000000000   
224.0000000000   -214.6625258400   192.0000000000   -35.7770876400   
17.8885438200   0.0000000000   -35.7770876400   20.0000000000   

eigenvectors: 
1.0000000000   0.0000000000   0.0000000000   0.0000000000   
0.0000000000   0.8944271910   0.0000000000   -0.4472135955   
0.0000000000   0.0000000000   1.0000000000   0.0000000000   
0.0000000000   0.4472135955   0.0000000000   0.8944271910   

iter 2: 
eigenvalues: 
346.1906658474   0.0000000000   122.5588355230   16.4723965268   
0.0000000000   1541.8093341526   -285.0181254504   -6.9756829533   
122.5588355230   -285.0181254504   192.0000000000   -35.7770876400   
16.4723965268   -6.9756829533   -35.7770876400   20.0000000000   

eigenvectors: 
0.9208349597   -0.3899525318   0.0000000000   0.0000000000   
0.3487841477   0.8236198263   0.0000000000   -0.4472135955   
0.000000

<ipython-input-109-840827a90ab2>:9: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(square_Sigma1), end='\n\n')


In [115]:
np.linalg.eig(np.matmul(A2.T, A2))

(array([1.60000000e+03, 4.00000000e+02, 1.00000000e+02, 1.36787883e-14]),
 array([[ 0.4, -0.8, -0.4, -0.2],
        [-0.8, -0.4,  0.2, -0.4],
        [ 0.2, -0.4,  0.8,  0.4],
        [-0.4, -0.2, -0.4,  0.8]]))

In [116]:
np.linalg.eig(np.matmul(A2, A2.T))

(array([ 1.60000000e+03,  4.00000000e+02, -9.77938613e-14,  1.00000000e+02]),
 array([[ 0.5,  0.5, -0.5,  0.5],
        [ 0.5, -0.5, -0.5, -0.5],
        [ 0.5,  0.5,  0.5, -0.5],
        [ 0.5, -0.5,  0.5,  0.5]]))

In [117]:
A3 = np.array([[6, -8, -4, 5, -4], 
               [2, 7, -5, -6, 4], 
               [0, -1, -8, 2, 2], 
               [-1, -2, 4, 4, -8]], dtype='float')

In [121]:
U, sigma, V = matrixStoring(A3.copy())

iter 1: 
eigenvalues: 
41.0000000000   -33.6277315857   -38.0000000000   -9.4432869490   -8.0000000000   
-33.6277315857   193.3416218956   -8.6568675623   0.0000000000   102.8699259710   
-38.0000000000   -8.6568675623   121.0000000000   5.8359784105   -52.0000000000   
-9.4432869490   0.0000000000   5.8359784105   5.6583781044   -8.8192023860   
-8.0000000000   102.8699259710   -52.0000000000   -8.8192023860   100.0000000000   

eigenvectors: 
1.0000000000   0.0000000000   0.0000000000   0.0000000000   0.0000000000   
0.0000000000   0.7736732733   0.0000000000   0.6335847742   0.0000000000   
0.0000000000   0.0000000000   1.0000000000   0.0000000000   0.0000000000   
0.0000000000   -0.6335847742   0.0000000000   0.7736732733   0.0000000000   
0.0000000000   0.0000000000   0.0000000000   0.0000000000   1.0000000000   

iter 2: 
eigenvalues: 
41.0000000000   -32.6003354113   -38.0000000000   -9.4432869490   11.4909730950   
-32.6003354113   259.6326906409   -35.4444086459   -4.77722687

0.2783900158   0.6120817737   -0.2882550382   0.6817359711   
0.6361191183   0.0000000000   0.7688214644   0.0653148008   
-0.3723162159   -0.5231679394   0.2463817758   0.7259283457   

iter 5: 
eigenvalues: 
148.3073406862   7.4610767961   -0.0579104220   0.0000000000   
7.4610767961   270.2204371803   0.0000000000   6.9375961237   
-0.0579104220   0.0000000000   21.4356381826   -2.5710949973   
0.0000000000   6.9375961237   -2.5710949973   21.0365839509   

eigenvectors: 
0.6158182376   -0.6128055509   -0.4911610487   0.0632303674   
0.2783900158   0.6002637367   -0.3121193861   0.6817359711   
0.6361191183   0.0302559234   0.7682258933   0.0653148008   
-0.3723162159   -0.5130666452   0.2667794780   0.7259283457   

iter 6: 
eigenvalues: 
147.8524206138   0.0000000000   -0.0578030762   -0.4222180784   
0.0000000000   270.6753572527   -0.0035243947   6.9247362311   
-0.0578030762   -0.0035243947   21.4356381826   -2.5710949973   
-0.4222180784   6.9247362311   -2.5710949973   21.036

In [125]:
np.matmul(np.matmul(U, np.diag(sigma)), V.T)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [126]:
np.diag(sigma)

array([[1.64580472e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 1.21595165e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.87099750e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.30722921e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.92360771e-08]])

In [127]:
sigma

array([1.64580472e+01, 1.21595165e+01, 4.87099750e+00, 4.30722921e+00,
       2.92360771e-08])