# Ý tưởng phương pháp: 

Biến đổi ma trận $A$ về ma trận đồng dạng Frobenius $P$ có định thức đơn giản hơn. 

# Ý tưởng thuật toán:

- Trong các bước đều phải giả thiết $a_{i,i-1}^{(n-i+1)} \neq 0$ (đường chéo ở ngay dưới đường chéo chính). Nêu bằng 0 thì có hai trường hợp xảy ra: 
1. Mọi phần tử trong hàng đó đứng trước nó đều bằng $0$. Khi đó chỉ cần biến đổi với ma trận cấp 3, cuối cùng, det nhân thêm với ($a_{44} - \lambda$). 
2. Tạo ra ma trận $A' \sim A$ có phần tử $a_{i,i-1}^{(n-i+1)} \neq 0$ như sau: 
\begin{align}
A' = C^{-1}AC
\end{align}
với $C = C^{-1}$ là ma trận hoán vị cột 2 và cột 3 với nhau. 

- Tìm véc tơ riêng: 
\begin{align}
Ax = \lambda x
\end{align}
với 
\begin{align}
x = M_{1}^{-1}M_{2}^{-1}M_{3}^{-1}y, \quad y = [\lambda^{n-1} \quad \lambda^{n-2} \cdots \quad \lambda \quad 1]^T
\end{align}
với $n$ là cấp của ma trận vuông. 

- Với ma trận cấp n thì cần n - 1 phép biến đổi (dễ thấy vì đường chéo ngay dưới đường chéo chính có n - 1 phần tử).

- Vấn để là phải giải phương trình đa thức bậc n của ma trận Frobenius P để có các trị riêng trước đã, rồi sau đó mới có thể tìm được véc tơ riêng.

VD: 
    

In [2]:
import numpy as np 

In [6]:
C = np.array([[1, 0, 0, 0], 
              [0, 0, 1, 0], 
              [0, 1, 0, 0], 
              [0, 0, 0, 1]], dtype='float')

In [7]:
np.linalg.inv(C)

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.matmul(C, C)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
M1 = np.array([[1, 0, 0, 0], 
               [0, 1, 0, 0], 
               [4, 3, 2, 1], 
               [0, 0, 0, 1]], dtype='float')

In [15]:
np.linalg.inv(M1)

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [-2. , -1.5,  0.5, -0.5],
       [ 0. ,  0. ,  0. ,  1. ]])

# Thực hiện chương trình

In [93]:
def Danielevski(A): 
    n = len(A)
    M = np.identity(n)
    
    # vòng lặp các phần tử đường chéo ai,i-1: 
    for i in range(n - 1, 0, -1):
        # nếu ai,i-1 = 0: 
        if A[i, i - 1] == 0: 
            print("A[%d, %d] = 0. Cần hoán đổi cột." %(i, i - 1))
            flag = False  # cờ hiệu, True nếu đổi được cột, False nếu không có cột đổi.
            
            for j in range(i - 2, -1, -1): 
                if A[i, j] != 0: 
                    flag = True 
                    A[:,[i, j]] = A[:,[j, i]]  # đổi chỗ cột thứ i và cột thứ j cho nhau. 
                    A[[i, j],:] = A[[j, i],:]  # đổi chỗ hàng thứ i và hàng thứ j cho nhau. 
                    break 
             
            # TH1: Có phần tử đứng trước nó trong hàng đó # 0.
            if flag == True: 
                Mi = np.identity(n)
                # cho hàng thứ i của ma trận A lên một hàng vào ma trận M_i. 
                Mi[i - 1] = A[i]
                invMi = np.linalg.inv(Mi)
            
                # nhân M với invMi 
                M = np.matmul(M, invMi)
            
                A = np.matmul(A, invMi)
                A = np.matmul(Mi, A)
            
                print('A(%d) = :' %(n - i + 1))
                print(A)
                

            # TH2: mọi phần tử đứng trước nó trong hàng đó đều bằng 0.
            else: 
                print("\nMọi phần tử đứng trước A[%d, %d] trong hàng %d đều bằng 0." %(i, i - 1, i))
                pass # lúc này, phải thu nhỏ ma trận lại hơn. 
            
        # nếu ai,i-1 # 0:     
        else: 
            Mi = np.identity(n)
            # cho hàng thứ i của ma trận A lên một hàng vào ma trận M_i. 
            Mi[i - 1] = A[i]
            invMi = np.linalg.inv(Mi)
            
            # nhân M với invMi 
            M = np.matmul(M, invMi)
            
            A = np.matmul(A, invMi)
            A = np.matmul(Mi, A)
            
            print('A(%d) = :' %(n - i + 1))
            print(A)
            
    # thêm hệ số vào mảng coeff - đa thức đặc trưng. (hàng đầu tiên của A).         
    coeff = np.array([])
    coeff = np.append(coeff, 1)
    for i in range(n): 
        coeff = np.append(coeff, -A[0][i])
    print('\nDa thuc dac trung la: ')
    print(coeff)
            
    # tìm nghiệm của đa thức đặc trưng - tương ứng với các trị riêng lambda. 
    roots = np.roots(coeff)
    print("\nNghiệm (trị riêng) của đa thức đặc trưng là: ")
    print(roots)
    print()
            
    # tìm các véc tơ riêng tương ứng với các giá trị riêng vừa tìm được ở trên. 
    for e in roots: 
        y = np.zeros(n)
    
        for i in range(n): 
            y[i] = e**(n - 1 - i)
        
        eigvec = np.matmul(M, y)
        print(e, eigvec)  # in cặp giá trị riêng - véc tơ riêng ra màn hình. 

    return A, M

VD1 (SGK):

In [90]:
A1 = np.array([[1, 2, 3, 4], 
              [2, 1, 2, 3], 
              [3, 2, 1, 2], 
              [4, 3, 2, 1]], dtype='float')

In [92]:
A1, M1 = Danielevski(A1)

A(2) = :
[[ -5.   -2.5   1.5   2.5]
 [ -2.   -2.    1.    2. ]
 [-24.  -15.   11.   19. ]
 [  0.    0.    1.    0. ]]
A(3) = :
[[-1.00000000e+00  1.66666667e-01 -3.33333333e-01 -6.66666667e-01]
 [ 6.00000000e+00  5.00000000e+00  3.40000000e+01  2.40000000e+01]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]]
A(4) = :
[[ 4.0000000e+00  4.0000000e+01  5.6000000e+01  2.0000000e+01]
 [ 1.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00 -8.8817842e-16]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00  0.0000000e+00]]

Da thuc dac trung la: 
[  1.  -4. -40. -56. -20.]

Nghiệm (trị riêng) của đa thức đặc trưng là: 
[ 9.09901951 -3.41421356 -1.09901951 -0.58578644]

9.099019513592784 [1.        0.8198039 0.8198039 1.       ]
-3.414213562373094 [-1.         -0.41421356  0.41421356  1.        ]
-1.0990195135927874 [ 1.        -1.2198039 -1.2198039  1.       

VD2: 

In [94]:
A2 = np.array([[1, -2, 1, 2, 3], 
               [-2, 3, 4, 5, 6], 
               [0, 0, 1, -2, 1], 
               [0, 0, 1, 0, 0], 
               [0, 0, 0, 1, 0]], dtype='float')

In [95]:
A2, M2 = Danielevski(A2)

A(2) = :
[[ 1. -2.  1.  2.  3.]
 [-2.  3.  4.  5.  6.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]
A(3) = :
[[ 1. -2.  1.  2.  3.]
 [-2.  3.  4.  5.  6.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]
A[2, 1] = 0. Cần hoán đổi cột.

Mọi phần tử đứng trước A[2, 1] trong hàng 2 đều bằng 0.
A(5) = :
[[  4.   1.   3. -11.  -8.]
 [  1.   0.   0.   0.   0.]
 [  0.   0.   1.  -2.   1.]
 [  0.   0.   1.   0.   0.]
 [  0.   0.   0.   1.   0.]]

Da thuc dac trung la: 
[ 1. -4. -1. -3. 11.  8.]

Nghiệm (trị riêng) của đa thức đặc trưng là: 
[ 4.23371588+0.j         1.54937064+0.j        -0.59325399+1.3009047j
 -0.59325399-1.3009047j -0.59657853+0.j       ]

(4.233715878607509+0j) [ 2.6217347  75.8866058  17.92435014  4.23371588  1.        ]
(1.5493706385506392+0j) [14.37221777  3.71934072  2.40054938  1.54937064  1.        ]
(-0.5932539936506764+1.3009046968604585j) [ 3.33375263  2.80318966 -1.34040273 -0.59325399  1.        ]
(-0.5932539936506764-

<ipython-input-93-9e7b655cdfee>:76: ComplexWarning: Casting complex values to real discards the imaginary part
  y[i] = e**(n - 1 - i)
