# Các lưu ý:
1. Chuẩn hàng ma trận và chuẩn cột ma trận không tương đương nhau. Nhưng lại tương đương với chuẩn Euclide.
2. Ta sẽ chỉ kiểm tra chuẩn hàng và rồi chuẩn cột. Không kiểm tra chuẩn Euclide.
3.

# 1. Các hàm cần dùng

### 1.1. Hàm tính chuẩn hàng của ma trận

In [2]:
def rowMatrixNorm(A):
    n = len(A)
    maxRowSum = 0.0
    
    for j in range(n): 
        maxRowSum += abs(A[0][j]) # tính tổng trị tuyệt đối của hàng 1, và tạm thời gán nó là max_row. 
        
    for i in range(1, n): 
        sum = 0 
        for j in range(n): 
            sum += abs(A[i][j])
            
        if sum > maxRowSum: 
            maxRowSum = sum
            
    return maxRowSum

### 1.2 Hàm tính chuẩn cột của ma trận:

In [3]:
def colMatrixNorm(A):
    n = len(A)
    maxColSum = 0.0
    
    for i in range(n): 
        maxColSum += abs(A[i][0]) # tính tổng trị tuyệt đối của hàng 1, và tạm thời gán nó là max_row. 
        
    for j in range(1, n): 
        sum = 0 
        for i in range(n): 
            sum += abs(A[i][j])
            
        if sum > maxColSum: 
            maxColSum = sum
            
    return maxColSum

### 1.3. Hàm tính chuẩn cực đại của véc tơ:

In [4]:
def maxVectorNorm(x): 
    n = len(x)
    max = abs(x[0])
    
    for i in range(1, n): 
        if abs(x[i]) > max: 
            max = abs(x[i])
            
    return max

### 1.4. Hàm tính chuẩn tuyệt đối của véc tơ: 

In [5]:
def absVectorNorm(x): 
    norm = 0 
    
    for i in range(len(x)): 
        norm += abs(x[i])
        
    return norm 

# 2. Phương pháp lặp đơn

In [6]:
import numpy as np
import math
import sys

### 2.1. Hàm biến đổi A thành alpha, b thành beta. 

In [7]:
def Transform(A, b): 
    n = len(A)
    I = np.identity(n)
    
    # Bien doi theo cong thuc dau tien: alpha = I - A, beta = b.
    alpha = I - A
    beta = b
    
    if rowMatrixNorm(alpha) < 1.0: 
        print('Ma trận I - A thỏa mãn chuẩn hàng.')
        return alpha, beta, 'row'
    elif colMatrixNorm(alpha) < 1.0: 
        print('Ma trận I - A thỏa mãn chuẩn cột.')
        return alpha, beta, 'col'
    
    # Bien doi theo cong thuc thu hai: alpha = I + A, beta = b.
    alpha = I + A
    beta = -b 
    
    if rowMatrixNorm(alpha) < 1: 
        print('Ma trận I + A thỏa mãn chuẩn hàng.')
        return alpha, beta, 'row'
    elif colMatrixNorm(alpha) < 1: 
        print('Ma trận I + A thỏa mãn chuẩn cột.')
        return alpha, beta, 'col'
    
    # Neu ca hai cong thuc tren dau khong thanh cong thi tra ve None. 
    print('Ma trận không thỏa mãn điều kiện lặp đơn.')
    sys.exit()

### 2.2. Hàm lặp tiên nghiệm.

Lưu ý: 
- Chuẩn  hàng của ma trận đi với chuẩn cực đại của véc tơ (đều là chuẩn vô cùng). 
- Chuẩn cột của ma trận đi với chuẩn tuyệt đối của véc tơ (đều là chuẩn 1).

In [8]:
def TienNghiem(alpha, beta, norm):
    n = len(alpha) 
    
    print('alpha = ', alpha)
    print('beta = ', beta)
    
    print('Nhap vao sai so tien nghiem: ')
    error = float(input())
                  
    x0 = np.zeros(n)
    x = np.matmul(alpha, x0) + beta
    print('x0 = ', x0)
    print('x = ', x)
    print()
    
    if norm == 'row': 
        alNorm = rowMatrixNorm(alpha)
        print('Chuẩn hàng của alpha = %f' % (alNorm))
        k = math.ceil(math.log(error * (1 - alNorm) / maxVectorNorm(x - x0), alNorm))  # chú ý có đảo dấu do cơ số alNorm < 1.
        print('k = %d' % (k))
        
        for i in range(k): 
            x = np.matmul(alpha, x) + beta
    elif norm == 'col': 
        alNorm = colMatrixNorm(alpha)
        print('Chuẩn cột của alpha = %f' % (alNorm))
        k = math.ceil(math.log(error * (1 - alNorm) / absVectorNorm(x - x0), alNorm)) # chú ý có đảo dấu do cơ số alNorm < 1.
        print('k = %d' % (k))
        
        for i in range(k): 
            x = np.matmul(alpha, x) + beta
    
    return x, k

In [17]:
A = np.array([[1, 0.4, -0.3], 
     [0.3, 1.1, -0.3], 
     [0.2, -0.1, 1.3]], dtype='float')

b = np.array([0.5, 0.4, 0.7], dtype='float')

Lặp với chuẩn hàng: 

In [18]:
TienNghiem(np.identity(len(A)) - A, b, 'row')

alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so tien nghiem: 
0.001
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn hàng của alpha = 0.700000
k = 22


(array([0.5027027 , 0.35984556, 0.48880309]), 22)

Lặp với chuẩn cột: 

In [19]:
TienNghiem(np.identity(len(A)) - A, b, 'col')

alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so tien nghiem: 
0.001
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn cột của alpha = 0.900000
k = 92


(array([0.5027027 , 0.35984556, 0.48880309]), 92)

### 2.3. Hàm lặp hậu nghiệm

In [9]:
def HauNghiem(alpha, beta, norm): 
    n = len(alpha)
    k = 1
    
    print('alpha = ', alpha)
    print('beta = ', beta)
    
    print('Nhap vao sai so hau nghiem: ')
    error = float(input())
                  
    x0 = np.zeros(n)
    x = np.matmul(alpha, x0) + beta
    print('x0 = ', x0)
    print('x = ', x)
    print()
    
    if norm == 'row': 
        alNorm = rowMatrixNorm(alpha)
        print('Chuẩn hàng của alpha = %f' % (alNorm))
        while alNorm * maxVectorNorm(x - x0) / (1 - alNorm) >= error: 
            x0 = x
            x = np.matmul(alpha, x0) + beta
            k += 1
    elif norm == 'col': 
        alNorm = colMatrixNorm(alpha)
        print('Chuẩn cột của alpha = %f' % (alNorm))
        while alNorm * absVectorNorm(x - x0) / (1 - alNorm) >= error: 
            x0 = x
            x = np.matmul(alpha, x0) + beta
            k += 1
    
    return x, k

In [21]:
A = np.array([[1, 0.4, -0.3], 
     [0.3, 1.1, -0.3], 
     [0.2, -0.1, 1.3]], dtype='float')

b = np.array([0.5, 0.4, 0.7], dtype='float')

In [22]:
HauNghiem(np.identity(len(A)) - A, b, 'row')

alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so hau nghiem: 
0.001
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn hàng của alpha = 0.700000


(array([0.50276357, 0.35990924, 0.48871994]), 9)

In [23]:
HauNghiem(np.identity(len(A)) - A, b, 'col')

alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so hau nghiem: 
0.001
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn cột của alpha = 0.900000


(array([0.50269219, 0.35983512, 0.48880074]), 12)

### 2.4. Hàm thực thi chính của phương pháp lặp đơn.

Hai công thức đánh giá sai số:
- Công thức sai số hậu nghiệm: 
\begin{align}
\Vert x^* - x^{(k)} \Vert_p \leq \frac{\Vert \alpha \Vert}{1 - \Vert \alpha \Vert}\Vert x^{(k)} - x^{(k-1)} \Vert_p, \qquad p = \infty, 1, 2
\end{align}
-Công thức sai số tiên nghiệm: 
\begin{align}
\Vert x^* - x^{(k)} \Vert_p \leq \frac{\Vert \alpha \Vert^k}{1 - \Vert \alpha \Vert}\Vert x^{(1)} - x^{(0)} \Vert_p, \qquad p = \infty, 1, 2
\end{align}

Ví dụ: 

In [10]:
def LapDon(A, b):
    n = len(A)
    
    alpha, beta, norm = Transform(A, b)
    
    print('Nhap vao su lua chon cua bạn: ')
    print('1. Lặp tiên nghiệm.')
    print('2. Lặp hậu nghiệm.')
    choice = input('Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: ')
    if choice == '1': 
        x, k = TienNghiem(alpha, beta, norm)
    elif choice == '2':
        x, k = HauNghiem(alpha, beta, norm)
    
    return x, k

Ví dụ 1: 

In [30]:
A = np.array([[1, 0.4, -0.3], 
     [0.3, 1.1, -0.3], 
     [0.2, -0.1, 1.3]], dtype='float')

b = np.array([0.5, 0.4, 0.7], dtype='float')

In [31]:
LapDon(A, b)  # ok

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 1
alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so tien nghiem: 
1e-5
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn hàng của alpha = 0.700000
k = 35


(array([0.5027027 , 0.35984556, 0.48880309]), 35)

In [32]:
LapDon(A, b)  # ok

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 2
alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so hau nghiem: 
1e-5
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn hàng của alpha = 0.700000


(array([0.50270279, 0.35984564, 0.48880344]), 15)

Ví dụ 2: SGK trang 67

In [33]:
A1 = np.array([[4, 0.24, -0.08], 
              [0.09, 3, -0.15], 
              [0.04, -0.08, 4]], dtype='float')

b1 = np.array([8, 9, 20])

In [34]:
LapDon(A1, b1)

Ma trận không thỏa mãn điều kiện lặp đơn.


SystemExit: 

# 2. Phương pháp lặp Jacobi

### 2.1. Hàm kiểm tra tính chéo trội hàng của ma trận.

In [11]:
def rowDominant(A): 
    n = len(A)
    
    # kiểm tra chéo trội hàng. 
    for i in range(n): 
        sum = 0 
        for j in range(n): 
            if j != i: 
                sum += abs(A[i][j])
        
        if abs(A[i][i]) <= sum: 
            return False 
        
    return True 

### 2.2. Hàm kiểm tra tính chéo trội cột của ma trận. 

In [12]:
def colDominant(A): 
    n = len(A)
    
    for j in range(n): 
        sum = 0
        for i in range(n): 
            if i != j: 
                sum += abs(A[i][j])
                
        if abs(A[j][j]) <= sum: 
            return False 
        
    return True 

In [38]:
A1 = np.array([[1, 0.5, 0.4], 
               [0.2, 1.5, 0.8], 
               [1, 0.6, 2]], dtype='float')

In [39]:
colDominant(A1)

False

- Định lý: Nếu A chéo trội hàng hoặc chéo trội cột thì A là ma trận khả nghịch, suy ra với mọi b, hệ luôn có nghiệm duy nhất.

### 2.3. Jacobi cho ma trận chéo trội hàng

In [13]:
def rowJacobi(A, b): 
    n = len(A)
    
    for i in range(n): 
        temp = A[i][i]
        A[i] = A[i] / temp
        b[i] = b[i] / temp
        
    print('TA = ', A)
    print('Tb = ', b)
    print()
        
    alpha = np.identity(n) - A   # alpha lúc này trở thành ma trận chéo trội hàng. 
    beta = b
    x0 = np.zeros(n)
    x = np.matmul(alpha, x0) + beta
    
    # Áp dụng trực tiếp các công thức sai số của lặp đơn. 
    print('Bạn muốn lặp chéo trội hàng bằng công thức tiên nghiệm hay hậu nghiệm: ')
    print('Tiên nghiệm: Ấn 1.')
    print('Hậu nghiệm: Ấn 2.')
    choice = int(input())
    
    print('Nhập vào sai số: ')
    error = float(input())
    
    alNorm = rowMatrixNorm(alpha)
    print('Chuẩn hàng của alpha = %f' % (alNorm))
    
    if choice == 1: # Lặp tiên nghiệm.
        k = math.ceil(math.log(error * (1 - alNorm) / maxVectorNorm(x - x0), alNorm))  # chú ý có đảo dấu do cơ số alNorm < 1.
        print('k = %d' % (k))
        
        for i in range(k): 
            x = np.matmul(alpha, x) + beta
    elif choice == 2: # Lặp hậu nghiệm.
        alNorm = rowMatrixNorm(alpha)
        k = 1 

        while alNorm * maxVectorNorm(x - x0) / (1 - alNorm) >= error: 
            x0 = x.copy()
            x = np.matmul(alpha, x0) + beta
            k += 1
    
    return x, k

### 2.4. Jacobi cho ma trận chéo trội cột (phức tạp hơn).

- Công thức lặp trực tiếp cho x: 
\begin{align}
x^{(n)} = Bx^{(n-1)} + d, \quad B = I - TA, d = Tb
\end{align}

Thiết lập công thức sai số trực tiếp đối với x: 
- Sai số tiên nghiệm: 
\begin{align}
\Vert x^{(n)} - x^* \Vert_1 \leq \frac{\max|a_{ii}|}{\min |a_{ii}|}\frac{q^n}{1 - q}\Vert x^{(1)} - x^{(0)}\Vert_1
\end{align}
- Sai số hậu nghiệm: 
\begin{align}
\Vert x^{(n)} - x^* \Vert_1 \leq \frac{\max|a_{ii}|}{\min |a_{ii}|}\frac{q}{1 - q}\Vert x^{(n)} - x^{(n-1)}\Vert_1
\end{align}
với: 
\begin{align}
q = \Vert B_1 \Vert_1 = \Vert I - AT \Vert_1 
\end{align}

In [14]:
def colJacobi(A, b): 
    n = len(A)
    
    # Ý tưởng: Tách Ax = b thành tổ hợp tuyến tính của các cột. 
    # Đặt ẩn phụ y_i = a_ii x_i , i = 1,..., n. Hệ trở thành By = b đã ở dạng chéo trội cột. 
    # Biến đổi By = b thành y = B_1 y + b, với B_1 = I - B. Tiến hành lặp với biến y hoặc x. 
    
    T = np.identity(n, dtype='float')
    for i in range(n): 
        T[i][i] = T[i][i] / A[i][i]
        
    print('T = ', T)
    print()
    
    alpha = np.identity(n) - np.matmul(T, A)
    beta = np.matmul(T, b)
    q = colMatrixNorm(np.identity(n) - np.matmul(A, T))  # chuẩn cột của ma trận I - AT. 
    print('Chuẩn cột của alpha: %f' % (q))
    
    # Tính lamda. 
    max = abs(T[0][0])
    for i in range(1, n): 
        if abs(T[i][i]) > max: 
            max = abs(T[i][i])
            
    min = abs(T[0][0])
    for i in range(1, n): 
        if abs(T[i][i]) < min: 
            min = abs(T[i][i])
    lamda = max / min
        
    print('TA = ', A)
    print('Tb = ', b)
    print()
    
    # Ta sẽ áp dụng công thức sai số trực tiếp lên x. 
    print('Bạn muốn lặp theo công thức sai số hậu nghiệm hoặc tiên nghiệm:')
    print('Tiên nghiệm: Ấn 1.')
    print('Hậu nghiệm: Ấn 2.')
    choice = int(input())
    
    print('Nhập vào sai số: ')
    error = float(input())
    
    x0 = np.zeros(n)
    x = np.matmul(alpha, x0) + beta
    
    if choice == 1: 
        k = math.ceil(math.log(error * (1 - q) / (lamda * absVectorNorm(x - x0)), q))
        
        for i in range(k): 
            x = np.matmul(alpha, x) + beta
    elif choice == 2: 
        k = 1
        while lamda * q * absVectorNorm(x - x0) / (1 - q) >= error: 
            x0 = x
            x = x = np.matmul(alpha, x0) + beta
            k += 1
    
    return x, k

### 2.5. Hàm thực thi chính.

In [15]:
def mainJacobi(A, b): 
    if rowDominant(A): 
        print('Ma trận là chéo trội hàng.')
        x, k = rowJacobi(A, b)
    elif colDominant(A): 
        print('Ma trận là chéo trội cột.')
        x, k = colJacobi(A, b)
    else: 
        return 'Ma trận A không chéo trội.'
    
    return x, k

In [45]:
# ma trận chéo trội hàng (không chéo trội cột).
A3 = np.array([[15, -5, 2], 
               [10, 35, -18], 
               [8, 4, 15]], dtype='float')

b3 = np.array([7, 12, 5], dtype='float')

- Trội hàng, lặp hậu nghiệm:

In [46]:
mainJacobi(A3, b3)  

Ma trận là chéo trội hàng.
TA =  [[ 1.         -0.33333333  0.13333333]
 [ 0.28571429  1.         -0.51428571]
 [ 0.53333333  0.26666667  1.        ]]
Tb =  [0.46666667 0.34285714 0.33333333]

Bạn muốn lặp chéo trội hàng bằng công thức tiên nghiệm hay hậu nghiệm: 
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
2
Nhập vào sai số: 
0.001


(array([ 0.53044649,  0.19096731, -0.00056961]), 13)

- Trội hàng, lặp tiên nghiệm:

In [47]:
mainJacobi(A3, b3)

Ma trận là chéo trội hàng.
TA =  [[ 1.         -0.33333333  0.13333333]
 [ 0.28571429  1.         -0.51428571]
 [ 0.53333333  0.26666667  1.        ]]
Tb =  [0.46666667 0.34285714 0.33333333]

Bạn muốn lặp chéo trội hàng bằng công thức tiên nghiệm hay hậu nghiệm: 
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
1
Nhập vào sai số: 
0.001
Chuẩn hàng của alpha = 0.800000
k = 35


(array([ 5.30417295e-01,  1.91050779e-01, -5.02765142e-04]), 35)

Ma trận chéo trội cột (không chéo trội hàng):

In [19]:
A4 = np.array([[10, 8, 7], 
              [3, -15, 14], 
              [-5, 2, 24]], dtype='float')

b4 = np.array([2, 6, 13], dtype='float')

In [20]:
mainJacobi(A4.copy(), b4.copy())

Ma trận là chéo trội cột.
T =  [[ 0.1         0.          0.        ]
 [ 0.         -0.06666667  0.        ]
 [ 0.          0.          0.04166667]]

Chuẩn cột của alpha: 0.875000
TA =  [[ 10.   8.   7.]
 [  3. -15.  14.]
 [ -5.   2.  24.]]
Tb =  [ 2.  6. 13.]

Bạn muốn lặp theo công thức sai số hậu nghiệm hoặc tiên nghiệm:
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
1
Nhập vào sai số: 
1e-3


(array([-0.17766867,  0.03291508,  0.50190944]), 75)

In [21]:
mainJacobi(A4.copy(), b4.copy())

Ma trận là chéo trội cột.
T =  [[ 0.1         0.          0.        ]
 [ 0.         -0.06666667  0.        ]
 [ 0.          0.          0.04166667]]

Chuẩn cột của alpha: 0.875000
TA =  [[ 10.   8.   7.]
 [  3. -15.  14.]
 [ -5.   2.  24.]]
Tb =  [ 2.  6. 13.]

Bạn muốn lặp theo công thức sai số hậu nghiệm hoặc tiên nghiệm:
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
2
Nhập vào sai số: 
1e-3


(array([-0.17767439,  0.03290272,  0.50190068]), 28)

# 3. Các ví dụ.

## 3.1. Lặp đơn

In [58]:
A = np.array([[1, 0.4, -0.3], 
              [0.3, 1.1, -0.3], 
              [0.2, -0.1, 1.3]], dtype='float')

b = np.array([0.5, 0.4, 0.7], dtype='float')

In [59]:
LapDon(A, b)

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 1
alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so tien nghiem: 
1e-5
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn hàng của alpha = 0.700000
k = 35


(array([0.5027027 , 0.35984556, 0.48880309]), 35)

In [60]:
LapDon(A, b)

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 2
alpha =  [[ 0.  -0.4  0.3]
 [-0.3 -0.1  0.3]
 [-0.2  0.1 -0.3]]
beta =  [0.5 0.4 0.7]
Nhap vao sai so hau nghiem: 
1e-5
x0 =  [0. 0. 0.]
x =  [0.5 0.4 0.7]

Chuẩn hàng của alpha = 0.700000


(array([0.50270279, 0.35984564, 0.48880344]), 15)

Ví dụ 2: 

In [61]:
A2 = np.array([[0.47, 0.034, 0.033, 0.028, 0.038, 0.004, 0.037], 
               [0.029, 0.187, 0.054, 0.045, 0.01, 0.041, 0.018], 
               [0.057, 0.075, 0.203, 0.071, 0.057, 0.021, 0.064], 
               [0.068, 0.075, 0.084, 0.310, 0.057, 0.041, 0.048], 
               [0.031, 0.30, 0.015, 0.047, 0.13, 0.028, 0.03], 
               [0.018, 0.007, 0.007, 0.017, 0.093, 0.165, 0.035], 
               [0.033, 0.029, 0.031, 0.022, 0.028, 0.042, 0.143]], dtype='float')  

b2 = np.array([0.75, 0.375, 0.3, 0.207, 0.2, 0.25, 0.27], dtype='float')

In [62]:
LapDon(A2, b2)

Ma trận không thỏa mãn điều kiện lặp đơn.


SystemExit: 

Ví dụ 3: 

In [63]:
A3 = np.array([[-1.1, 0.1, 0, -0.3, 0.1], 
               [0, -0.3, 0.1, 0, -0.1], 
               [-0.1, 0, -0.5, -0.2, 0], 
               [0.2, 0, -0.2, -1, 0.3], 
               [-0.1, -0.1, 0, 0.4, -0.8]], dtype='float')

b3 = np.array([-0.2, 1.3, -2, 0.7, 0.8], dtype='float')

In [64]:
LapDon(A3, b3)

Ma trận I + A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 1
alpha =  [[-0.1  0.1  0.  -0.3  0.1]
 [ 0.   0.7  0.1  0.  -0.1]
 [-0.1  0.   0.5 -0.2  0. ]
 [ 0.2  0.  -0.2  0.   0.3]
 [-0.1 -0.1  0.   0.4  0.2]]
beta =  [ 0.2 -1.3  2.  -0.7 -0.8]
Nhap vao sai so tien nghiem: 
1e-5
x0 =  [0. 0. 0. 0. 0.]
x =  [ 0.2 -1.3  2.  -0.7 -0.8]

Chuẩn hàng của alpha = 0.900000
k = 138


(array([ 0.40096432, -2.12671167,  4.77126326, -2.12864031, -1.84860174]), 138)

In [65]:
LapDon(A3, b3)

Ma trận I + A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 2
alpha =  [[-0.1  0.1  0.  -0.3  0.1]
 [ 0.   0.7  0.1  0.  -0.1]
 [-0.1  0.   0.5 -0.2  0. ]
 [ 0.2  0.  -0.2  0.   0.3]
 [-0.1 -0.1  0.   0.4  0.2]]
beta =  [ 0.2 -1.3  2.  -0.7 -0.8]
Nhap vao sai so hau nghiem: 
1e-5
x0 =  [0. 0. 0. 0. 0.]
x =  [ 0.2 -1.3  2.  -0.7 -0.8]

Chuẩn hàng của alpha = 0.900000


(array([ 0.400964  , -2.12671439,  4.77126319, -2.12864007, -1.84860098]), 44)

Nhận xét: Số lần lặp hậu nghiệm giảm đi đáng kể so với tiên nghiệm, ở đây q = ||alpha|| ở gần 1 nên gây ra độ lệch lớn về số vòng lặp giữa hai sai số.

Ví dụ 4: Khi chuẩn của alpha quá gần 1. 

In [66]:
A4 = np.array([[1, 0.4999, 0.5], 
               [0.4999, 1, 0.5], 
               [0.5, 0.4999, 1]], dtype='float')

b4 = np.array([1.0, 1.1, 1.2], dtype='float')

In [67]:
LapDon(A4, b4)

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 1
alpha =  [[ 0.     -0.4999 -0.5   ]
 [-0.4999  0.     -0.5   ]
 [-0.5    -0.4999  0.    ]]
beta =  [1.  1.1 1.2]
Nhap vao sai so tien nghiem: 
1e-6
x0 =  [0. 0. 0.]
x =  [1.  1.1 1.2]

Chuẩn hàng của alpha = 0.999900
k = 232071


(array([0.3500375 , 0.54999751, 0.7500375 ]), 232071)

In [68]:
LapDon(A4, b4)

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 2
alpha =  [[ 0.     -0.4999 -0.5   ]
 [-0.4999  0.     -0.5   ]
 [-0.5    -0.4999  0.    ]]
beta =  [1.  1.1 1.2]
Nhap vao sai so hau nghiem: 
1e-6
x0 =  [0. 0. 0.]
x =  [1.  1.1 1.2]

Chuẩn hàng của alpha = 0.999900


(array([0.3500375 , 0.54999751, 0.7500375 ]), 231200)

In [69]:
LapDon(A4, b4)

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 1
alpha =  [[ 0.     -0.4999 -0.5   ]
 [-0.4999  0.     -0.5   ]
 [-0.5    -0.4999  0.    ]]
beta =  [1.  1.1 1.2]
Nhap vao sai so tien nghiem: 
1e-5
x0 =  [0. 0. 0.]
x =  [1.  1.1 1.2]

Chuẩn hàng của alpha = 0.999900
k = 209046


(array([0.3500375 , 0.54999751, 0.7500375 ]), 209046)

In [70]:
LapDon(A4, b4)

Ma trận I - A thỏa mãn chuẩn hàng.
Nhap vao su lua chon cua bạn: 
1. Lặp tiên nghiệm.
2. Lặp hậu nghiệm.
Bạn muốn lặp theo công thức sai số tiên nghiệm hay hậu nghiệm: 2
alpha =  [[ 0.     -0.4999 -0.5   ]
 [-0.4999  0.     -0.5   ]
 [-0.5    -0.4999  0.    ]]
beta =  [1.  1.1 1.2]
Nhap vao sai so hau nghiem: 
1e-5
x0 =  [0. 0. 0.]
x =  [1.  1.1 1.2]

Chuẩn hàng của alpha = 0.999900


(array([0.3500375 , 0.54999751, 0.7500375 ]), 208176)

Nhận xét: Dù alpha rất gần 1, nhưng số lần lặp của thuật toán tiên nghiệm là hậu nghiệm là rất lớn. Vì thế khi alpha -> 1 thì độ bất ổn và số lần lặp của hệ cũng sẽ tăng lên rất cao.

## 3.2. Lặp Jacobi

Ví dụ 1: Ma trận trội hàng: 

In [82]:
A1 = np.array([[7.7, 1.2, 1.1, 2.1], 
               [2.4, 17.4, 2.6, 2.2], 
               [1.1, 1.3, 8.3, 1.0], 
               [4.2, 2.2, 2.0, 9.8]])

b1 = np.array([9.8, 4.6, 2.1, 14])

In [81]:
mainJacobi(A1, b1)

Ma trận là chéo trội hàng.
TA =  [[1.         0.15584416 0.14285714 0.27272727]
 [0.13793103 1.         0.14942529 0.12643678]
 [0.13253012 0.15662651 1.         0.12048193]
 [0.42857143 0.2244898  0.20408163 1.        ]]
Tb =  [1.27272727 0.26436782 0.25301205 1.42857143]

Bạn muốn lặp chéo trội hàng bằng công thức tiên nghiệm hay hậu nghiệm: 
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
1
Nhập vào sai số: 
1e-5
Chuẩn hàng của alpha = 0.857143
k = 90


(array([1., 0., 0., 1.]), 90)

In [83]:
mainJacobi(A1, b1)

Ma trận là chéo trội hàng.
TA =  [[1.         0.15584416 0.14285714 0.27272727]
 [0.13793103 1.         0.14942529 0.12643678]
 [0.13253012 0.15662651 1.         0.12048193]
 [0.42857143 0.2244898  0.20408163 1.        ]]
Tb =  [1.27272727 0.26436782 0.25301205 1.42857143]

Bạn muốn lặp chéo trội hàng bằng công thức tiên nghiệm hay hậu nghiệm: 
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
2
Nhập vào sai số: 
1e-5
Chuẩn hàng của alpha = 0.857143


(array([1.00000039e+00, 2.80755728e-07, 2.76428201e-07, 1.00000051e+00]), 25)

Ví dụ 2: Giải phương trình với cả trội hàng và trội cột.

In [84]:
A2 = np.array([[5.1, 1.1, 1.2, 1.0], 
               [1.1, 6.1, 1.0, 1.1], 
               [1.2, 1.0, 7.1, 1.0], 
               [1.0, 1.1, 1.0, 5.1]])

b2 = np.array([6.3, 2.1, 8.3, 2.0])

In [85]:
mainJacobi(A2, b2)

Ma trận là chéo trội hàng.
TA =  [[1.         0.21568627 0.23529412 0.19607843]
 [0.18032787 1.         0.16393443 0.18032787]
 [0.16901408 0.14084507 1.         0.14084507]
 [0.19607843 0.21568627 0.19607843 1.        ]]
Tb =  [1.23529412 0.3442623  1.16901408 0.39215686]

Bạn muốn lặp chéo trội hàng bằng công thức tiên nghiệm hay hậu nghiệm: 
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
1
Nhập vào sai số: 
1e-5
Chuẩn hàng của alpha = 0.647059
k = 30


(array([1.00000001e+00, 5.81449411e-09, 1.00000001e+00, 6.46419052e-09]), 30)

In [86]:
mainJacobi(A2, b2)

Ma trận là chéo trội hàng.
TA =  [[1.         0.21568627 0.23529412 0.19607843]
 [0.18032787 1.         0.16393443 0.18032787]
 [0.16901408 0.14084507 1.         0.14084507]
 [0.19607843 0.21568627 0.19607843 1.        ]]
Tb =  [1.23529412 0.3442623  1.16901408 0.39215686]

Bạn muốn lặp chéo trội hàng bằng công thức tiên nghiệm hay hậu nghiệm: 
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
2
Nhập vào sai số: 
1e-5
Chuẩn hàng của alpha = 0.647059


(array([ 9.99998652e-01, -1.16391170e-06,  9.99998966e-01, -1.29396417e-06]),
 22)

Nhận xét: Vì A đỗi xứng qua đường chéo chính nên chuẩn hàng và chuẩn cột trong ví dụ này là bằng nhau, và vì vậy số lần lặp ở hai trường hợp trội hàng và trội cột là tương đương nhau.

Ví dụ 3: Ma trận trội cột (không trội hàng)

In [87]:
A4 = np.array([[10, 8, 7], 
              [3, -15, 14], 
              [-5, 2, 24]], dtype='float')

b4 = np.array([2, 6, 13], dtype='float')

In [88]:
mainJacobi(A4, b4)

Ma trận là chéo trội cột.
T =  [[ 0.1         0.          0.        ]
 [ 0.         -0.06666667  0.        ]
 [ 0.          0.          0.04166667]]

Chuẩn cột của alpha: 0.875000
TA =  [[ 10.   8.   7.]
 [  3. -15.  14.]
 [ -5.   2.  24.]]
Tb =  [ 2.  6. 13.]

Bạn muốn lặp theo công thức sai số hậu nghiệm hoặc tiên nghiệm:
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
1
Nhập vào sai số: 
1e-5


(array([-0.17766867,  0.03291508,  0.50190944]), 110)

In [89]:
mainJacobi(A4, b4)

Ma trận là chéo trội cột.
T =  [[ 0.1         0.          0.        ]
 [ 0.         -0.06666667  0.        ]
 [ 0.          0.          0.04166667]]

Chuẩn cột của alpha: 0.875000
TA =  [[ 10.   8.   7.]
 [  3. -15.  14.]
 [ -5.   2.  24.]]
Tb =  [ 2.  6. 13.]

Bạn muốn lặp theo công thức sai số hậu nghiệm hoặc tiên nghiệm:
Tiên nghiệm: Ấn 1.
Hậu nghiệm: Ấn 2.
2
Nhập vào sai số: 
1e-5


(array([-0.17766887,  0.03291513,  0.50190941]), 41)

# 4. Ma trận trội không trên đường chéo chính.